project:
  type: book
  
execute:
  cache: false

book:
  title: "데이터 분석 방법론 "
  author: "이용희"
  date: "9/5/2023"
  repo-url: https://github.com/ilovedata/statmehods
  downloads: [pdf]
  chapters:
    - index.qmd
    - notes/intro.qmd
    - part: "분할표의 분석"
      chapters:
        - notes/association.qmd
        - notes/association-test.qmd
        - notes/diagnose.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
#    lang: kr
    language: custom.yml
    code-fold: false
    code-overflow: wrap
    embed-resources: false
    toc: true
    toc-depth: 2
    theme: cosmo
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    fig-cap-location: top
    css: styles.css
#    include-in-header:
#      - latex/preamble-mathjax.tex
  pdf:
    documentclass: scrbook
    #documentclass: scrreprt
    papersize: A4
    lang: kr
    fontsize: 10pt
    lof: true
    lot: true
    code-overflow: wrap
    language: custom.yml
    latex-auto-install: true
    latex-tinytex: true
    pdf-engine: xelatex
    include-in-header: latex/preamble.tex