<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.395">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>데이터 분석 방법론 - 5&nbsp; 로지스틱 회귀모형</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notes/poisson.html" rel="next">
<link href="../notes/diagnose.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script type="text/javascript">
 window.MathJax = {
  tex: {
    macros: {
    RR: '{\\mathbb R}',                    // a simple string replacement
    hatmat:'{\\pmb X ({\\pmb X}^t {\\pmb X} )^{-1} {\\pmb X}^t}',
    bold: ['\\boldsymbol{#1}',1] ,     // this macro has one parameter
    pardiff: ['\\frac{\\partial#2}{\\partial#1}', 2, 'x'], // this macro has an optional parameter that defaults to 'x'
    pardifftwo: ['\\frac{\\partial#1}{\\partial#2}', 2]
  },
  environments: {
  braced: ["\\left\\{", "\\right\\}"]
  }
 }
};
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notes/logistic.html">일반화 선형모형</a></li><li class="breadcrumb-item"><a href="../notes/logistic.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">로지스틱 회귀모형</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">데이터 분석 방법론</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ilovedata/statmehods" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../데이터-분석-방법론-.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="검색"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">서론</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">분할표의 분석</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/association.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">연관성의 측도</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/association-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">연관성의 검정</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/diagnose.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">진단의 평가</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">일반화 선형모형</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/logistic.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">로지스틱 회귀모형</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">포아송 회귀모형</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#필요한-패키지" id="toc-필요한-패키지" class="nav-link active" data-scroll-target="#필요한-패키지"><span class="header-section-number">5.1</span> 필요한 패키지</a></li>
  <li><a href="#이항변수-예제" id="toc-이항변수-예제" class="nav-link" data-scroll-target="#이항변수-예제"><span class="header-section-number">5.2</span> 이항변수: 예제</a>
  <ul class="collapse">
  <li><a href="#sec-oring" id="toc-sec-oring" class="nav-link" data-scroll-target="#sec-oring"><span class="header-section-number">5.2.1</span> 챌린져호 O-ring 자료</a></li>
  <li><a href="#sec-blowdown" id="toc-sec-blowdown" class="nav-link" data-scroll-target="#sec-blowdown"><span class="header-section-number">5.2.2</span> 강풍에 의한 나무 피해 자료</a></li>
  </ul></li>
  <li><a href="#로지스틱-회귀모형" id="toc-로지스틱-회귀모형" class="nav-link" data-scroll-target="#로지스틱-회귀모형"><span class="header-section-number">5.3</span> 로지스틱 회귀모형</a>
  <ul class="collapse">
  <li><a href="#이항변수와-연결함수" id="toc-이항변수와-연결함수" class="nav-link" data-scroll-target="#이항변수와-연결함수"><span class="header-section-number">5.3.1</span> 이항변수와 연결함수</a></li>
  <li><a href="#예제" id="toc-예제" class="nav-link" data-scroll-target="#예제"><span class="header-section-number">5.3.2</span> 예제</a></li>
  <li><a href="#회귀계수의-해석" id="toc-회귀계수의-해석" class="nav-link" data-scroll-target="#회귀계수의-해석"><span class="header-section-number">5.3.3</span> 회귀계수의 해석</a></li>
  </ul></li>
  <li><a href="#추정과-검정" id="toc-추정과-검정" class="nav-link" data-scroll-target="#추정과-검정"><span class="header-section-number">5.4</span> 추정과 검정</a>
  <ul class="collapse">
  <li><a href="#이항분포와-가능도-함수" id="toc-이항분포와-가능도-함수" class="nav-link" data-scroll-target="#이항분포와-가능도-함수"><span class="header-section-number">5.4.1</span> 이항분포와 가능도 함수</a></li>
  <li><a href="#편차" id="toc-편차" class="nav-link" data-scroll-target="#편차"><span class="header-section-number">5.4.2</span> 편차</a></li>
  <li><a href="#검정과-모형의-선택" id="toc-검정과-모형의-선택" class="nav-link" data-scroll-target="#검정과-모형의-선택"><span class="header-section-number">5.4.3</span> 검정과 모형의 선택</a></li>
  <li><a href="#적합도-검정" id="toc-적합도-검정" class="nav-link" data-scroll-target="#적합도-검정"><span class="header-section-number">5.4.4</span> 적합도 검정</a></li>
  </ul></li>
  <li><a href="#과산포" id="toc-과산포" class="nav-link" data-scroll-target="#과산포"><span class="header-section-number">5.5</span> 과산포</a>
  <ul class="collapse">
  <li><a href="#과산포의-개요" id="toc-과산포의-개요" class="nav-link" data-scroll-target="#과산포의-개요"><span class="header-section-number">5.5.1</span> 과산포의 개요</a></li>
  <li><a href="#예제-1" id="toc-예제-1" class="nav-link" data-scroll-target="#예제-1"><span class="header-section-number">5.5.2</span> 예제</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notes/logistic.html">일반화 선형모형</a></li><li class="breadcrumb-item"><a href="../notes/logistic.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">로지스틱 회귀모형</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="logistic" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">로지스틱 회귀모형</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="필요한-패키지" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="필요한-패키지"><span class="header-section-number">5.1</span> 필요한 패키지</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(epiR)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(faraway)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sm)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="이항변수-예제" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="이항변수-예제"><span class="header-section-number">5.2</span> 이항변수: 예제</h2>
<p>먼저 R을 이용한 로지스틱 회귀분석을 소개하기 위하여 다음의 예제를 이용하고자 한다.</p>
<section id="sec-oring" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="sec-oring"><span class="header-section-number">5.2.1</span> 챌린져호 O-ring 자료</h3>
<p>1986년 미국우주항공국(NASA)이 발사한 우주왕복선 챌린져호(Spache Shuttle Challenger)가 로켓 엔진에 주요부품인 O-rings의 손상으로 인하여 공중에서 폭팔하는 사고가 일어났다. 다음 데이타는 미국우주항공국이 챌린져호를 발사하기 전에 실험을 통하여 얻은자료이다. 디음의 자료는 교과서의 R package <code>faraway</code>에서 <code>orings</code>에서 볼 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#data(orings)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>orings <span class="sc">%&gt;%</span> <span class="fu">kbl</span>() <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>( <span class="at">full_width =</span> F)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">temp</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">damage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">53</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td style="text-align: right;">57</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">58</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">63</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">66</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">67</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">67</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">67</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">68</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">69</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">70</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">70</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">70</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">70</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">72</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">73</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">75</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">75</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">76</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">76</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">78</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">79</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">81</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>위의 자료에서 <code>temp</code>는 실험에서 적용된 온도(화씨 F)이고 <code>damage</code>는 각 실험마다 6개의 링중에서 손상된 개수를 나타낸다. 참고로 1986년 챌린져호가 발사될 때의 온도는 31F 였다.</p>
<p>먼저 그림을 통하여 온도의 변화에 따른 손상비율을 살펴보자.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(damage<span class="sc">/</span><span class="dv">6</span> <span class="sc">~</span> temp, orings, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">25</span>,<span class="dv">85</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">xlab=</span><span class="st">"Temperature"</span>, <span class="at">ylab=</span><span class="st">"Prob of damage"</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="sec-blowdown" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="sec-blowdown"><span class="header-section-number">5.2.2</span> 강풍에 의한 나무 피해 자료</h3>
<p>1999년 미국 Misnnesota주의 Boundary Waters Canoe Area Wilderness (BWCAW)에서 심한 폭풍으로 생긴 강한 바람에 의해 쓰러진 나무들에 대한 자료를 수집하였다. 이 자료는 <span class="citation" data-cites="weisberg4">Weisberg (<a href="../references.html#ref-weisberg4" role="doc-biblioref">2014</a>)</span> (R package <code>alr4</code>) 에 수록된 자료이다.</p>
<p>연구의 목적은 폭풍이 나무의 생존에 미치는 영향을 알아보는 것이다. 666 그루의 나무들에 대하여 나무가 바람에 의해 쓰러저 죽었는지 여부, 나무의 종, 나무의 지름, 폭풍의 국지적인 강도에 대한 자료를 수집하였다.</p>
<ul>
<li><code>d</code>: Tree diameter, in cm</li>
<li><code>s</code> : Proportion of basal area killed for the four species balsam fir, cedar, paper birch and blue spruse, a measure of local severity of the storm.</li>
<li><code>spp</code> : Tree species, a factor with 9 levels</li>
<li><code>y</code> : 1 if the tree died, 0 if it survived</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Blowdown) <span class="sc">%&gt;%</span> <span class="fu">kbl</span>() <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>( <span class="at">full_width =</span> F)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">d</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">s</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">y</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">spp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.0217509</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">balsam fir</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.0217509</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">balsam fir</td>
</tr>
<tr class="odd">
<td style="text-align: right;">18</td>
<td style="text-align: right;">0.0217509</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">balsam fir</td>
</tr>
<tr class="even">
<td style="text-align: right;">23</td>
<td style="text-align: right;">0.0217509</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">balsam fir</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.0217509</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">balsam fir</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: right;">0.0217509</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">balsam fir</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>반응변수 <span class="math inline">\(y\)</span> 를 쓰러진 나무는 <span class="math inline">\(y=1\)</span>로하고 살아남은 나무를 <span class="math inline">\(y=0\)</span>으로 코딩하였다. 나무의 상태 <code>y</code>에 나무의 지름 <code>d</code>이 미치는 영향을 살펴보려고 한다.</p>
<p>수집된 자료중에서 나무의 종류가 <code>black spruce</code>인 자료만를 분석하기로 한다. 아래 코드는 <code>black spruce</code>인 자료만를 모아서 데이터프레임 <code>BlowBS_raw</code> 를 만드는 것이다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>BlowBS_raw <span class="ot">&lt;-</span> Blowdown <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(spp<span class="sc">==</span><span class="st">'black spruce'</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(BlowBS_raw)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 659   4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(BlowBS_raw) <span class="sc">%&gt;%</span> <span class="fu">kbl</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>( <span class="at">full_width =</span> F)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">d</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">s</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">y</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">spp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.0242120</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">black spruce</td>
</tr>
<tr class="even">
<td style="text-align: right;">11</td>
<td style="text-align: right;">0.0305947</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">black spruce</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.0305947</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">black spruce</td>
</tr>
<tr class="even">
<td style="text-align: right;">9</td>
<td style="text-align: right;">0.0341815</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">black spruce</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0341815</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">black spruce</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.0341815</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">black spruce</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>아래 그림은 쓰러진 나무와 살아남은 나무들의 지름의 분포를 비교한 것이다. 이를 통하여 지름이 큰 나무가 살아남을 확률이 더 커짐을 알수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sm.density.compare</span>(BlowBS_raw<span class="sc">$</span>d, BlowBS_raw<span class="sc">$</span>y,<span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">xlab=</span><span class="st">"D"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="dv">30</span>,.<span class="dv">1</span>,<span class="at">legend=</span><span class="fu">c</span>(<span class="st">"Y=0"</span>,<span class="st">"Y=1"</span>),<span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sm.density.compare</span>(<span class="fu">log</span>(BlowBS_raw<span class="sc">$</span>d), BlowBS_raw<span class="sc">$</span>y,<span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">xlab=</span><span class="st">"log(D)"</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="fl">3.2</span>,.<span class="dv">9</span>,<span class="at">legend=</span><span class="fu">c</span>(<span class="st">"Y=0"</span>,<span class="st">"Y=1"</span>),<span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>또한 R package <code>alr4</code> 에 수록된 데이터셋 <code>BlowBS</code> 는 위에서 본 O-rings 예제와 동일하게 <code>black spruce</code>인 자료만 모아서 전체 횟수와 성공의 횟수로 요약된 자료이다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(BlowBS) <span class="sc">%&gt;%</span> <span class="fu">kbl</span>() <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>( <span class="at">full_width =</span> F)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">d</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">died</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">m</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">88</td>
</tr>
<tr class="even">
<td style="text-align: right;">5.5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6.0</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">91</td>
</tr>
<tr class="even">
<td style="text-align: right;">6.5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7.0</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">90</td>
</tr>
<tr class="even">
<td style="text-align: right;">7.5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>


</div>
</div>
<ul>
<li><code>d</code> :Tree diameter, in cm</li>
<li><code>died</code> : Number of trees of this value of d that died (blowdown)</li>
<li><code>m</code> : number of trees of this size class measured</li>
</ul>
<p>이제 데이터셋 <code>BlowBS</code> 를 이용하여 나무의 지름과 나무 피해의 관계에 대해서 살펴보자.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( died<span class="sc">/</span>m<span class="sc">~</span> d, BlowBS, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">xlab=</span><span class="st">"D"</span>, <span class="at">ylab=</span><span class="st">"Prob of Blow Down"</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>나무의 지름 <span class="math inline">\(d\)</span>을 <span class="math inline">\(\log(d)\)</span>로 변환하여 예측변수(predictor) <span class="math inline">\(x\)</span>로 하려고 한다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( died<span class="sc">/</span>m<span class="sc">~</span> <span class="fu">I</span>(<span class="fu">log</span>(d)), BlowBS, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">xlab=</span><span class="st">"log(D)"</span>, <span class="at">ylab=</span><span class="st">"Prob of Blow Down"</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>나무의 상태 <span class="math inline">\(y\)</span>는 두 가지의 반응 결과를 가지는 이항변수이고 그 평균 <span class="math inline">\(E(y)\)</span>는 0과 1사이의 값을 가지는 확률이지만 나무의 지름 <span class="math inline">\(x=\log(D)\)</span>는 연속형 변수이다.</p>
<p>이러한 경우에 <strong>회귀분석의 모형은 어떻게 세울까?</strong>에 대하여 생각해보자.</p>
<p><span class="math display">\[ 0 \le E(y|x) = p(x) \le 1, \quad \quad -\infty &lt; \beta_0 + \beta_1 x &lt; \infty \]</span></p>
</section>
</section>
<section id="로지스틱-회귀모형" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="로지스틱-회귀모형"><span class="header-section-number">5.3</span> 로지스틱 회귀모형</h2>
<section id="이항변수와-연결함수" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="이항변수와-연결함수"><span class="header-section-number">5.3.1</span> 이항변수와 연결함수</h3>
<p>일반적으로 지금까지 배워온 회귀분석의 확률 모형에서는 반응변수 <span class="math inline">\(y\)</span>는 연속형 확률변수이다. 따라서 예측변수 <span class="math inline">\(x\)</span>의 값과 반응변수의 관계를 다음과 같은 회귀식으로 설명한다.</p>
<p><span id="eq-ordinaryreg"><span class="math display">\[ E(y|x) =  \beta_0 + \beta_1 x  \tag{5.1}\]</span></span></p>
<p>하지만 앞에서 살펴본 예제에서와 같이 반응변수의 값이 연속형 변수가 아니라 두 개의 가능한 결과만을 가지는 이항변수라면 위에서 주어진 회귀식은 적절하지 못하다.</p>
<p><span class="math display">\[
y =
\begin{cases}
1 &amp; \text{ with probabilty } p \\
0 &amp; \text{ with probabilty } 1-p
\end{cases}
\]</span></p>
<p>왜냐하면 반응변수의 기대값이 0과 1사이의 확률로 나타나기 때문이다.</p>
<p><span class="math display">\[ E(y|x) = 1\cdot P(y=1|x) + 0 \cdot P(y=0|x) = P(y=1|x) \]</span></p>
<p>따라서 반응변수의 기대값의 범위와 예측변수가 있는 선형예측식(linear predictor) <span class="math inline">\(\beta_0 + \beta_1 x\)</span>의 범위가 일치하지 않아서 선형회귀식 <a href="#eq-ordinaryreg" class="quarto-xref">식&nbsp;<span>5.1</span></a> 을 그대로 사용할 수 없다.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>범위의 불일치</figcaption>
<p><img src="logistic_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>위의 문제를 해결하기 위한 방법중의 하나는 다음과 같은 함수 <span class="math inline">\(m\)</span>를 생각하여 변환된 선형예측식의 범위를 <span class="math inline">\([0,1]\)</span>로 만드는 것이다.</p>
<p><span class="math display">\[ m:\Re \rightarrow [0,1]  \quad \text{and } \quad m(x) \text{ is monotone function}. \]</span></p>
<p>따라서 다음과 같은 이항변수를 반응변수로 하는 새로운 회귀식을 만들 수있다.</p>
<p><span id="eq-logistic1"><span class="math display">\[  E(y|x) = m(\beta_0 + \beta_1 x)  \tag{5.2}\]</span></span></p>
<p>주로 쓰이는 변환함수로 다음과 같은 로지스틱 함수(logistic function)가 있다.</p>
<p><span id="eq-logisticfunc"><span class="math display">\[ m(x) = \frac{ \exp(\beta_0 + \beta_1 x) }{ 1+ \exp(\beta_0 + \beta_1 x) }  \tag{5.3}\]</span></span></p>
<p>반응변수가 베르누이 분포를 따를 때 위의 로지스틱홤수를 사용하는 회귀식을 로지스틱 회귀식이라고 한다.</p>
<p><span id="eq-logisticregression"><span class="math display">\[
P(y=1|x) = \frac{ \exp(\beta_0 + \beta_1 x) }{ 1+ \exp(\beta_0 + \beta_1 x) } =  \{ 1+ \exp[-(\beta_0 + \beta_1 x)] \}^{-1}
\tag{5.4}\]</span></span></p>
<p>위의 로지스틱 회귀식을 다시 역으로 정리하면 다음과 같은 식을 얻을 수 있다.</p>
<p><span id="eq-logit"><span class="math display">\[
\log \left [ \frac{P(y=1|x)}{1-P(y=1|x)} \right ] = \log \frac{p(x)}{1-p(x)}=\beta_0 + \beta_1 x
\tag{5.5}\]</span></span></p>
<p>식 <a href="#eq-logit" class="quarto-xref">식&nbsp;<span>5.5</span></a> 에서 나타난 함수 <span class="math inline">\(g\)</span>,</p>
<p><span class="math display">\[ g(p)=\log \frac{p}{1-p} \]</span></p>
<p>를 <strong>로짓함수(logit function)</strong> 라고 부르며 이는 로지스틱 함수의 역함수로서 0과 1 사이의 값을 가지는 확률을 실수 전체로 변환하는 함수로서 선형 예측식의 범위와 일치하게 한다.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>로지스틱 연결함수</figcaption>
<p><img src="logistic_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>이렇게 관측값의 평균 (베르누이분포에서는 성공확률)과 선형예측식의 관계를 설정하는 함수를 <strong>연결함수(link function)</strong> 라고 하며 <span class="math inline">\(g\)</span> 라고 표시한다.</p>
<p><span id="eq-linkfunction"><span class="math display">\[
g[E(y|x)] = g[p(x)] =  \log \frac{p(x)}{1-p(x)}=\beta_0 + \beta_1 x
\tag{5.6}\]</span></span></p>
<p>따라서 로짓함수는 연결함수의 하나이며 다른 종류의 연결함수도 생각할 수 있다. 예를 들어 <span class="math inline">\(\Phi(x)=P(Z \le x)\)</span>를 표준정규분포의 분포함수라 한다면 다음과 같은 연결함수를 생각할 수 있고 이를 probit 함수라고 부른다.</p>
<p><span class="math display">\[ g[p(x)] = \Phi^{-1}(p(x)) = \beta_0 + \beta_1 x \]</span></p>
<p>만약 예측변수가 하나가 아닌 <span class="math inline">\(p\)</span>개라면, 즉 예측변수 <span class="math inline">\({\pmb x}=(x_1,x_2,\dots,x_{p})^t\)</span> 에 대한 로지스틱 회귀모형은 다음과 같이 확장할 수 있다.</p>
<p><span class="math display">\[
\log \left [ \frac{P(y=1|x)}{1-P(y=1 | x)} \right  ] = \pmb x^t \pmb \beta = \beta_0 + \beta_1 x_{1} + \beta_2 x_2 +  \dots \beta_p x_{p}
\]</span></p>
</section>
<section id="예제" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="예제"><span class="header-section-number">5.3.2</span> 예제</h3>
<p>위의 o-ring 예제(<a href="#sec-oring" class="quarto-xref"><span>섹션&nbsp;5.2.1</span></a>)에서 성공(<span class="math inline">\(y=1\)</span>)은 O-ring이 손상된 경우이며 주어진 온도 <span class="math inline">\(x\)</span>에서의 손상확률을 <span class="math inline">\(p=(Y=1|x)=p(x)\)</span>라고 하면 다음과 같은 로지스틱회귀식을 생각할 수 있다.</p>
<p><span class="math display">\[ \log \frac{p(x)}{1-p(x)}=\beta_0 + \beta_1 x \]</span></p>
<p>다음과 같은 함수 <code>glm</code>을 이용하여 위의 로지스틱 회귀식을 적합할 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>logit1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(damage,<span class="dv">6</span><span class="sc">-</span>damage) <span class="sc">~</span> temp, <span class="at">family=</span>binomial, orings)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(damage, 6 - damage) ~ temp, family = binomial, 
    data = orings)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) 11.66299    3.29626   3.538 0.000403 ***
temp        -0.21623    0.05318  -4.066 4.78e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 38.898  on 22  degrees of freedom
Residual deviance: 16.912  on 21  degrees of freedom
AIC: 33.675

Number of Fisher Scoring iterations: 6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(logit1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        temp 
 11.6629897  -0.2162337 </code></pre>
</div>
</div>
<p>위의 결과에서 회귀식 기울기의 추정치는 <span class="math inline">\(\hat \beta=\)</span> -0.2162337이다. 따라서 다음과 같은 회귀식을 얻을 수 있다.</p>
<p><span class="math display">\[ \log \frac{p(x)}{1-p(x)}=11.6629897+ (-0.2162337) x \]</span> 위의 회귀식을 이용하여 추정된 고장확률을 그림으로 그려보면 다음과 같다.</p>
<p>여기서 <code>ilogit</code>은 로짓함수의 역함수를 계산해주며 다음과 같이 주어진 회귀식을 이용하여 확률을 계산한다.</p>
<p><span class="math display">\[ P(y=1|x) = \frac{ \exp(\beta_0 + \beta_1 x) }{ 1+ \exp(\beta_0 + \beta_1 x) } =  \frac{1}{ 1+ \exp[-(11.6629897+ (-0.2162337) x)] }\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(damage<span class="sc">/</span><span class="dv">6</span> <span class="sc">~</span> temp, orings, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">25</span>,<span class="dv">85</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">xlab=</span><span class="st">"Temperature"</span>, <span class="at">ylab=</span><span class="st">"Prob of damage"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">25</span>,<span class="dv">85</span>,<span class="dv">1</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x,<span class="fu">ilogit</span>(<span class="fu">coef</span>(logit1)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(logit1)[<span class="dv">2</span>]<span class="sc">*</span>x))</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>또한 온도가 31F인 경우 고장확률의 추정값은 <span class="math inline">\(\hat p =\)</span> 0.9930342이며 R 에서 다음과 같이 계산한다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">31</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ilogit</span>(<span class="fu">coef</span>(logit1)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(logit1)[<span class="dv">2</span>]<span class="sc">*</span>x)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
  0.9930342 </code></pre>
</div>
</div>
<p>이제 강풍에 의한 나무의 피해에 대한 예제(<a href="#sec-blowdown" class="quarto-xref"><span>섹션&nbsp;5.2.2</span></a>)에 대하여 로지스틱 회귀식을 적합해보자.나무의 상태 <span class="math inline">\(y\)</span> 가 이항 변수이고 나무의 지름 <span class="math inline">\(x=\log(d)\)</span>을 예측변수로 하는 로지스틱회귀 모형을 고려하고 추정해보면 다음과 같은 회귀식을 얻는다</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>logit2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(y<span class="sc">~</span> <span class="fu">I</span>(<span class="fu">log</span>(d)),<span class="at">family=</span><span class="fu">binomial</span>(),<span class="at">data=</span>BlowBS_raw)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit2)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ I(log(d)), family = binomial(), data = BlowBS_raw)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -7.8925     0.6325  -12.48   &lt;2e-16 ***
I(log(d))     3.2643     0.2761   11.82   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 856.21  on 658  degrees of freedom
Residual deviance: 655.24  on 657  degrees of freedom
AIC: 659.24

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><span class="math display">\[ \log \left [ \frac{P(y=1|x)}{1-P(y=1|x)} \right ]  =-7.892464+ (3.2642653) x \]</span> 위의 회귀식을 이용하여 추정된 나무가 부러져서 피해를 입을 확률은 다음과 같다.</p>
<p><span class="math display">\[ P(y=1|x) = \frac{ \exp(\beta_0 + \beta_1 x) }{ 1+ \exp(\beta_0 + \beta_1 x) } =  \frac{1}{ 1+ \exp[-(-7.892464+ (3.2642653) x)] }\]</span> 이제 나무의 지름에 변화에 대하여 나무가 부러져서 피해를 입을 확률의 추정값을 그림으로 그려보자.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( died<span class="sc">/</span>m<span class="sc">~</span> <span class="fu">I</span>(<span class="fu">log</span>(d)), BlowBS, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">xlab=</span><span class="st">"log(D)"</span>, <span class="at">ylab=</span><span class="st">"Prob of Blow Down"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="fl">3.5</span>,<span class="fl">0.1</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x,<span class="fu">ilogit</span>(<span class="fu">coef</span>(logit2)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(logit2)[<span class="dv">2</span>]<span class="sc">*</span>x))</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="logistic_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="회귀계수의-해석" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="회귀계수의-해석"><span class="header-section-number">5.3.3</span> 회귀계수의 해석</h3>
<p>일반적인 회귀분석의 모형 <a href="#eq-ordinaryreg" class="quarto-xref">식&nbsp;<span>5.1</span></a> 에서 계수 <span class="math inline">\(\beta_1\)</span>은 기울기로서 예측변수 <span class="math inline">\(x\)</span>의 단위가 1 증가할 때 반응변수의 평균이 <span class="math inline">\(\beta_1\)</span>만큼 증가하는 것으로 해석할 수 있다. 하지만 로지스틱 회귀모형 <a href="#eq-logisticregression" class="quarto-xref">식&nbsp;<span>5.4</span></a> 에서는 이러한 해석을 할 수 없다.</p>
<p>로지스틱 회귀모형에서 기울기 <span class="math inline">\(\beta_1\)</span>의 의미를 알아보기 위하여 예측변수 <span class="math inline">\(x\)</span> 에 대한 베르누이 변수 <span class="math inline">\(y\)</span>의 성공 확률 <span class="math inline">\(P(y=1|x)\)</span>에 대한 오드(odd)를 정의하자.</p>
<p><span class="math display">\[ odd(x) = \frac{P(y=1|x)}{1-P(y=1|x)} \]</span></p>
<p>이제 단순 로지스틱 회귀식 <a href="#eq-logit" class="quarto-xref">식&nbsp;<span>5.5</span></a> 을 생각하고 예측변수 <span class="math inline">\(x\)</span>를 0과 1의 값을 가지는 이항변수로 가정한다.</p>
<p><span class="math inline">\(x=1\)</span> 인 경우는</p>
<p><span class="math display">\[  \frac{P(y=1|x=1)}{1-P(y=1|x=1)}  = \exp( \beta_0 + \beta_1)  \]</span></p>
<p>이며 <span class="math inline">\(x=0\)</span> 인 경우는</p>
<p><span class="math display">\[ \frac{P(y=1|x=0)}{1-P(y=1|x=0)} = \exp(\beta_0)   \]</span></p>
<p>위에서 주어진 두 개의 오드, 즉 <span class="math inline">\(x=1\)</span>인 경우와 <span class="math inline">\(x=0\)</span>인 경우의 두 오드의 비(odd ratio)를 구하면 다음과 같다.</p>
<p><span class="math display">\[   \frac{ \frac{P(y=1|x=1)}{1-P(y=1|x=1)} } {\frac{P(y=1|x=0)}{1-P(y=1|x=0)}}  = \exp (\beta_1) \]</span></p>
<p>이는 다시 쓰면</p>
<p><span class="math display">\[   \frac{P(y=1|x=1)}{1-P(y=1|x=1)}   = \exp (\beta_1) \frac{P(y=1|x=0)}{1-P(y=1|x=0)} \]</span></p>
<p>위의 식에서 볼 떄 예측변수 <span class="math inline">\(x\)</span>가 1 의 값을 가질 때 반응 변수의 오드가 예측변수 <span class="math inline">\(x\)</span>가 0일 경우의 오드의 <span class="math inline">\(\exp (\beta_1)\)</span>배로 변하는 것을 알 수 있다.</p>
<p>따라서 <span class="math inline">\(\exp (\beta_1)\)</span>는 반응변수의 오드의 증가량으로 볼 수 있다. 이는 두 성공확률의 오즈비가 <span class="math inline">\(\exp (\beta_1)\)</span>을 말한다. 위의 식에 로그를 취하면 다음과 같은 관계를 얻는다.</p>
<p><span class="math display">\[  \log   \left [ \frac{P(y=1|x=1)}{1-P(y=1|x=1)}  / \frac{P(y=1|x=0)}{1-P(y=1|x=0)} \right ]  = \beta_1 \]</span></p>
<p>즉 오즈비의 로그값이 단순 로지스틱 회귀식에서 기울기 <span class="math inline">\(\beta_1\)</span>으로 나타난다.</p>
<p>간단한 예제를 통하여 오즈비와 로지스틱 회귀의 기울기의 관계를 명확히 해보자. 100명의 사람들을 55세 이상의 사람(<span class="math inline">\(x=1\)</span>)과 55세 미만의 사람(<span class="math inline">\(x=0\)</span>)의 그룹으로 나누었을 떄 각 그룹에서 만성심장질환(CHD)가 있는 사람(<span class="math inline">\(y=1\)</span>)과 없는 사람(<span class="math inline">\(y=0\)</span>)의 수가 표 <a href="#tbl-chd" class="quarto-xref">표&nbsp;<span>5.1</span></a> 에 주어져있다.</p>
<div id="tbl-chd" class="anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="table quarto-float-caption quarto-float-tbl" id="tbl-chd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
표&nbsp;5.1: 나이와 만성심장질환의 관계
</figcaption>
<div aria-describedby="tbl-chd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">CHD/나이</th>
<th style="text-align: center;">나이 <span class="math inline">\(\ge 55\)</span> (<span class="math inline">\(x=1\)</span>)</th>
<th style="text-align: center;">나이 <span class="math inline">\(&lt; 55\)</span> (<span class="math inline">\(x=0\)</span>)</th>
<th style="text-align: center;">합계</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">CHD 있음 <span class="math inline">\(y=1\)</span></td>
<td style="text-align: center;">21</td>
<td style="text-align: center;">22</td>
<td style="text-align: center;">43</td>
</tr>
<tr class="even">
<td style="text-align: center;">CHD 없음 <span class="math inline">\(y=0\)</span></td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">51</td>
<td style="text-align: center;">57</td>
</tr>
<tr class="odd">
<td style="text-align: center;">합계</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">73</td>
<td style="text-align: center;">100</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>여기서 나이에 대한 CHD 유무의 오즈비는 다음과 같이 계산된다.</p>
<p><span class="math display">\[ \text{Odds Ratio } = \frac{ \tfrac{21/27}{6/27}}{ \tfrac{22/73}{51/73}} =  \frac{(21)(51)}{(6)(22)} = 8.11 \]</span></p>
<p>위의 표 <a href="#tbl-chd" class="quarto-xref">표&nbsp;<span>5.1</span></a> 의 자료를 이용하여 로지스틱회귀를 적합시키면 결과가 아래와 같고 회귀계수 <span class="math inline">\(\beta_1\)</span>의 추정값은 오즈비의 로그값임을 알 수 있다.</p>
<p><span class="math display">\[ \hat \beta_1 = \log (8.11) = 2.094  \]</span></p>
<p>표 <a href="#tbl-chd" class="quarto-xref">표&nbsp;<span>5.1</span></a> 의 자료에 대하여 로지스틱 회귀모형은 다음과 같이 적합할 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>yes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">21</span>,<span class="dv">22</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>no  <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">51</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span> (<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">glm</span>( <span class="fu">cbind</span>(yes,no) <span class="sc">~</span> x, <span class="at">family=</span><span class="fu">binomial</span>() )</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(yes, no) ~ x, family = binomial())

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)  -0.8408     0.2551  -3.296  0.00098 ***
x             2.0935     0.5285   3.961 7.46e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1.8704e+01  on 1  degrees of freedom
Residual deviance: 1.4211e-14  on 0  degrees of freedom
AIC: 11.987

Number of Fisher Scoring iterations: 3</code></pre>
</div>
</div>
</section>
</section>
<section id="추정과-검정" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="추정과-검정"><span class="header-section-number">5.4</span> 추정과 검정</h2>
<section id="이항분포와-가능도-함수" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="이항분포와-가능도-함수"><span class="header-section-number">5.4.1</span> 이항분포와 가능도 함수</h3>
<p>주어진 예측변수 <span class="math inline">\(x_i\)</span>에서 실행횟수가 <span class="math inline">\(m_i\)</span>인 이항분포<span class="math inline">\(B(m_i, p(x_i))\)</span>를 생각하자. <span class="math inline">\(m_i\)</span>의 시행 중에 성공의 횟수가 <span class="math inline">\(y_i\)</span>라고 하면 <span class="math inline">\(y_i\)</span>의 확률밀도함수는 다음과 같다.</p>
<p><span class="math display">\[ {{m_i}\choose{y_i}} {p(x_i)}^{y_i} [(1-p(x_i)]^{m_i-y_i} \]</span></p>
<p>그리고 <span class="math inline">\(y_i\)</span>의 평균과 분산은 다음과 같다.</p>
<p><span class="math display">\[ E(y_i | x_i ) = m_i p(x_i), \quad \quad Var(y_i | x_i) = m_i p(x_i) [1-p(x_i)] , \quad i=1,2,\dots,n \]</span></p>
<p>이항분포를 위한 로지스틱 회귀방정식은 선형예측식과 성공의 확률의 관계를 다음과 같이 정한다.</p>
<p><span class="math display">\[ \log \left [ \frac{p(x_i)}{1-p(x_i)} \right  ] =  \beta_0 + \beta_1 x_{i}  \]</span></p>
<p>서로 독립인 관측값 <span class="math inline">\((y_1,y_2,\dots,y_n)\)</span>의 가능도함수(likelihood function) <span class="math inline">\(L\)</span>은 이항분포들의 결합확률밀도함수와 같고 아래와 같이 주어지며</p>
<p><span class="math display">\[ L = \prod_{i=1}^n f(y_i|p(x_i)) = \prod_{i=1}^n \left [  {{m_i}\choose{y_i}} \right] {p(x_i)}^y_i {(1-p(x_i))}^{m-y_i}
\]</span></p>
<p>로그가능도함수(log likelihood function) <span class="math inline">\(l\)</span> 은 다음과 같이 나타낼 수 있다.</p>
<p><span class="math display">\[\begin{align}
l  &amp; = \log L \\
&amp; = \sum_i \log {{m_i}\choose{y_i}} + \sum_i y_i \log p(x_i) + \sum_i (m_i -y_i) \log [1-p(x_i)]  \notag  \\
   &amp; = c(\pmb y,\pmb m) + \sum_i y_i \log \left [ \frac{p(x_i)}{1-p(x_i)} \right  ] + \sum_i m_i \log [1-p(x_i)]  \end{align}\]</span></p>
<p>결론적으로</p>
<p><span id="eq-bionom-loglike"><span class="math display">\[ l(\pmb \mu|\pmb y)  = \log L(\pmb \mu|\pmb y) =  c(\pmb y,\pmb m) + \sum_i y_i \log \left [ \frac{p(x_i)}{1-p(x_i)} \right  ] + \sum_i m_i \log [1-p(x_i)]   \tag{5.7}\]</span></span></p>
<p>위의 로그가능도함수에서 볼 수 있듯이 충분통계량인 성공의 횟수 <span class="math inline">\(y_i\)</span>와 곱으로 나타내어진 함수가 로짓함수이며 이렇게 가능도함수에서 얻어진 결합함수를 자연 연결함수(natural link function)이라고 한다.</p>
<p>회귀계수의 추정량은 최대가능도 추정법을 이용하여 구할 수 있으며 로그 가능도 함수가 회귀계수에 대하여 비선형이므로 반복을 이용한 계산법에 의하여 추정량을 얻을 수 있다.</p>
<p><span class="math display">\[ \max_{\pmb \beta } \log L = \max_{\pmb \beta } \sum_i y_i \log \left [ \frac{p(x_i)}{1-p(x_i)} \right  ] + \sum_i m_i \log [1-p(x_i)] \]</span></p>
</section>
<section id="편차" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="편차"><span class="header-section-number">5.4.2</span> 편차</h3>
<p>선형모형에서 잔차제곱합(residual sum of square; SSE)에 대한 의미를 살펴보고 이를 일반화 선형모형에 확장하는 개념인 편차(deviance)의 정의를 알아보자.</p>
<p>먼저 다음과 같은 선형회귀식을 고려한다.</p>
<p><span class="math display">\[ y_i = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + \dots \beta_p x_{pi} + e_i , \quad i=1,2,\dots,n \]</span></p>
<p>여기서 오차항 <span class="math inline">\(e_i\)</span>를 서로 독립이며 평균이 0이고 분산이 <span class="math inline">\(\sigma^2\)</span>인 정규분포를 따른다고 가정하고 (<span class="math inline">\(\sigma^2\)</span>는 알고있다고 가정하자) 각 관측변수의 평균을 다음과 같이 <span class="math inline">\(\mu_i\)</span>로 하자.</p>
<p><span class="math display">\[   \mu_i =E(y_i|x_i)= \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + \dots +\beta_p x_{pi} \]</span></p>
<p>서로 독립인 관측변수 <span class="math inline">\(y_i\)</span>의 분포는 정규분포를 따르므로</p>
<p><span class="math display">\[ y_i \sim N(\mu_i,\sigma^2)   \]</span></p>
<p>관측치 <span class="math inline">\(\pmb y=(y_1,y_2,\dots,y_n)^t\)</span>의 로그가능도함수는 다음과 같이 나타낼 수 있다.</p>
<p><span class="math display">\[ l(\pmb \mu|\pmb y) = C -\frac{n}{2} \log \sigma^2 -\frac{1}{2\sigma^2} \sum_{i=1}^n (y_i - \mu_i)^2 \]</span></p>
<p>예측변수 <span class="math inline">\(x_1,x_2,\dots,x_p\)</span>를 고려한 선형회귀모형에서 각 반응변수 평균의 예측식은 다음과 같다.</p>
<p><span class="math display">\[ \hat \mu_i = \hat \beta_0 + \hat \beta_1 x_{1i} + \hat \beta_2 x_{2i} + \dots +\hat \beta_p x_{pi} \equiv \hat y_i \]</span></p>
<p>이 때 선형회귀모형의 로그가능도함수의 최대값는 다음과 같다.</p>
<p><span class="math display">\[\begin{align*}
l(\hat{\pmb \mu}|\pmb y) &amp; = l_{regession}(\hat {\pmb \beta}|y) \\
&amp; = C -\frac{n}{2} \log \sigma^2 -\frac{1}{2\sigma^2} \sum_{i=1}^n (y_i - \hat \mu_i)^2  \\
  &amp;= C -\frac{n}{2} \log \sigma^2 -\frac{1}{2\sigma^2} \sum_{i=1}^n (y_i - \hat y_i)^2  \\
   &amp;= C -\frac{n}{2} \log \sigma^2 -\frac{1}{2\sigma^2} SSE
\end{align*}\]</span></p>
<p>이제 위의 선형회귀모형에서 예측변수 <span class="math inline">\(x_1,x_2,\dots,x_p\)</span>를 고려하지 않는 포화 모형을 생각해보자.</p>
<p><span class="math display">\[ y_i = \beta_{0i} +e_i \quad \text{or} \quad E(y_i) = \beta_{0i} \]</span></p>
<p>이러한 포화 모형은 <span class="math inline">\(n\)</span>개의 반응변수의 평균을 <span class="math inline">\(n\)</span>개의 모수를 가진 모형으로 추정하는 것으로 위와 같은 모형을 포화 모형(saturated model)이라고 한다. 포화 모형에서 모수 <span class="math inline">\(\beta_{0i}\)</span>의 최소제곱 추정량(또는 최대가능도 추정량)는 관측값 <span class="math inline">\(y_i\)</span>임을 쉽게 알수 있다.</p>
<p><span class="math display">\[ \min_{\beta_{0i}} \sum_{i=1}^n (y_i -\beta_{0i})^2 \quad \Rightarrow \hat \beta_{0i} = y_i, \quad i=1,2,\dots,n
\]</span></p>
<p>포화 모형의 의미는 우리가 생각할 수 있는 모형 중에 가장 큰 모형으로 포화모형보다 큰 모형을 생각할 수 없다. 위에서 언급한 바와 같이 <span class="math inline">\(n\)</span>개의 관측값에 대하여 모수의 수가 <span class="math inline">\(n\)</span>개보다 큰 모형을 생각하면 유일한 모수의 추정이 불가능하다.</p>
<p>선형회귀모형에서 포화모형은 <span class="math inline">\(\hat \beta_{0i}=y_i\)</span>이며 로그가능도함수의 최대값은 <span class="math inline">\(l(\pmb y | \pmb y)\)</span>로 표시하며 다음과 같다.</p>
<p><span class="math display">\[\begin{align*}
l(\pmb y | \pmb y) &amp; = l_{saturated}(\hat {\pmb \beta_{0}} | y) \\
&amp; = C -\frac{n}{2} \log \sigma^2 -\frac{1}{2\sigma^2} \sum_{i=1}^n (y_i - \hat \beta_{0i})^2  \\
&amp;= C -\frac{n}{2} \log \sigma^2 -\frac{1}{2\sigma^2} \sum_{i=1}^n (y_i - y_i)^2  \\
   &amp;= C -\frac{n}{2} \log \sigma^2 + 0
\end{align*}\]</span></p>
<p>포화모형은 설정할 수 있는 최대의 모수를 가진 가장 큰 모형이므로 우리가 생각할 수 있는 모형 중에서 관측값을 예측하는 예측력은 가장 좋다는 것을 알 수 있다(하지만 과적합모형이다).</p>
<p>따라서 예측변수 <span class="math inline">\(\pmb x\)</span>들을 사용하는 선형회귀모형의 예측력이 포화모형이 가지는 예측력에 가까우면 좋은 모형이라고 생각할 수 있다. 반응변수의 평균을 예측하는 예측력은 로그가능도함수의 크기로서 나타낼 수 있다. 포화모형과 선형회귀모형의 로그가능도함수를 비교하면 포화모형의 로그가능도함수가 크다는 것을 알수 있고 (why?) 두 로그가능도함수의 의 차이를 비교하면 다음과 같다.</p>
<p><span class="math display">\[
l(\pmb y | \pmb y) - l(\hat {\pmb \mu} | \pmb y) = l_{saturated}(\hat {\pmb \beta_{0}} | y) -l_{regession}(\hat {\pmb \beta}|y) = \frac{1}{2\sigma^2} \sum_{i=1}^n (y_i - \hat y_i)^2 = \frac{1}{2\sigma^2}  SSE
\]</span></p>
<p>위의 식을 가능도 함수의 비율로 다음과 같이 나타낼 수 있다.</p>
<p><span class="math display">\[ 2 \log \frac{L_{saturated}}{L_{regession}} =
\frac{1}{\sigma^2} \sum_{i=1}^n (y_i - \hat y_i)^2 = \frac{1}{\sigma^2}  SSE  \]</span></p>
<p>따라서 포화모형과 로그가능도함수의의 차이가 작다는 것은 선형회귀모형의 잔차제곱합(SSE)이 작다는 것을 의미한다. 보통 잔차제곱합이 작으면 선형회귀모형의 예측력이 좋은 모형이며 이는 선형회귀모형의 가능도함수가 포화모형의 가능도함수에 가깝다는 의미이다.</p>
<p>이렇게 모형의 예측능력을 평가하는 측도로서 편차(deviance)를 포화모형과 고려한 회귀모형의 로그가능도함수의 차이에 2를 곱한 양으로 정의한다. 따라서 편차는 작을 수록 좋다.</p>
<p><span id="eq-deviance"><span class="math display">\[ deviance \equiv D(\pmb y;\hat {\pmb \mu}) = 2 \left [ l(\pmb y | \pmb y) - l(\hat {\pmb \mu} | \pmb y) \right ] = 2 \log \frac{L_{saturated}}{L_{regession}}
\tag{5.8}\]</span></span></p>
<p>정규분포인 경우 편차는 다음과 같이 주어진다.</p>
<p><span class="math display">\[
D(\pmb y;\hat {\pmb \mu}) = 2 \left [ l(\pmb y | \pmb y) - l(\hat {\pmb \mu} | \pmb y) \right ] =
\frac{1}{\sigma^2}  SSE \]</span></p>
<p>이제 이항분포들에서 나온 관측값에 대한 포화모형을 생각해 보자.</p>
<p><span class="math display">\[ y_i \sim B(m_i, p_i(x_i)), \quad i=1,2,\dots,n \]</span></p>
<p>위의 모형에서 포화모형은 어떤 모형일까? 포화모형은 <span class="math inline">\(n\)</span>개의 관측변수의 평균, 여기서 <span class="math inline">\(E(y_i/m_i) = p(\pmb x_i)\)</span>를 <span class="math inline">\(n\)</span>개의 관측치 <span class="math inline">\(y_i\)</span>를 이용하여 추정한 모형으로서 각 성공확률은 해당하는 관측된 성공의 비율에 의해 추정된다. 즉,</p>
<p><span class="math display">\[ \hat p(x_i) = \frac{y_i}{m_i} \]</span></p>
<p>이러한 경우의 로그가능도함수의 값은 다음과 같이 주어진다.</p>
<p><span class="math display">\[\begin{align*}
l(\pmb y | \pmb y)  &amp; =l_{saturated} \\
&amp; = \sum_i \log {{m_i}\choose{y_i}} + \sum_i y_i \log \hat p(x_i) + \sum_i (m_i -y_i) \log (1- \hat p(x_i))  \\
&amp; = \sum_i \log {{m_i}\choose{y_i}} + \sum_i y_i \log  \frac{y_i}{m_i} + \sum_i (m_i -y_i) \log (1- \frac{y_i}{m_i})
\end{align*}\]</span></p>
<p>따라서 위에서 주어진 포화함수의 로그가능도함수에서 로지스틱회귀식의 로그가능도함수 <a href="#eq-bionom-loglike" class="quarto-xref">식&nbsp;<span>5.7</span></a> 를 빼고 2를 곱해서 편차를 정의할 수 있다.</p>
<p><span class="math display">\[\begin{align*}
D(\pmb y;\hat {\pmb \mu}) &amp;=  2 \left [ l(\pmb y | \pmb y) - l(\hat {\pmb \mu} | \pmb y) \right ] \\
&amp;= 2 ( l_{saturated}-l_{regession})  \\
   &amp; = 2 \left [\sum_i y_i \log  \frac{y_i}{m_i} + \sum_i (m_i -y_i) \log (1- \frac{y_i}{m_i})
    -\sum_i y_i \log \hat p(x_i) - \sum_i (m_i -y_i) \log (1-\hat p(x_i)) \right ]\\
   &amp; = 2\left  [\sum_i y_i \log \frac{y_i}{m_i \hat p(x_i) } + \sum_i (m_i -y_i) \log \frac{1-y_i/m_i}{1-\hat p(x_i)}\right ] \\
   &amp; = 2\left [\sum_i y_i \log  \frac{y_i}{m_i \hat p(x_i) } + \sum_i (m_i -y_i) \log \frac{m_i-y_i}{m_i- m_i \hat p(x_i)} \right ] \\
   &amp; = 2\left  [\sum_i y_i \log   \frac{y_i}{\hat y_i } + \sum_i (m_i -y_i) \log \frac{m_i-y_i}{m_i- \hat y_i } \right ]\\
\end{align*}\]</span></p>
<p>위에서 <span class="math inline">\(\hat y_i = m_i \hat p(x_i)\)</span>으로 로지스틱 회귀에서 성공의 횟수의 평균에 대한 예측값이다.</p>
<p>위의 논의에서 알 수 있듯이 로지스틱 회귀에서의 편차는 선형회귀 분석에서 잔차 제곱합 SSE의 의미로 해석할 수 있으며 작을 수록 모형의 예측력이 좋다는 것을 알 수 있다.</p>
<div class="callout callout-style-default callout-important callout-titled" title="편차의 점근적 분포">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
편차의 점근적 분포
</div>
</div>
<div class="callout-body-container callout-body">
<p>편차는 표본의 개수 <span class="math inline">\(m_i\)</span>가 충분히 크고 회귀식이 옳다는 가정 하에서 자유도가 <span class="math inline">\(n-p\)</span> 인 카이제곱분포를 따른다. 여기서 <span class="math inline">\(p\)</span>는 회귀계수 벡터 <span class="math inline">\(\pmb \beta\)</span>의 크기이다.</p>
<p><span class="math display">\[  D(\pmb y;\hat {\pmb \mu}) \sim \chi^2_{n-p} \]</span></p>
<p>여기서 <span class="math inline">\(n= \sum_i m_i\)</span> 이고 <span class="math inline">\(p\)</span> 는 회귀계수의 갯수이다.</p>
</div>
</div>
<p>정규분포와 이항분포의 편차를 비교하면 정규분포의 편차에는 산포를 나타내는 모수 <span class="math inline">\(\sigma^2\)</span> 이 포함되어 있지만 이항분포의 편차에는 다른 모수가 나타나지 않는다. 식 <a href="#eq-deviance" class="quarto-xref">식&nbsp;<span>5.8</span></a> 에서 주어진 편차를 척도 모수(scaled parameter) 또는 산포 모수(dispersion parameter) <span class="math inline">\(\phi\)</span> 를 곱해준 값을 척도화 편차(scaled deviance) <span class="math inline">\(D^*(\pmb y;\hat {\pmb \mu})\)</span> 라고 부른다.</p>
<p><span id="eq-scaleddeviance"><span class="math display">\[ D^*(\pmb y;\hat {\pmb \mu}) = \phi D(\pmb y;\hat {\pmb \mu})  \tag{5.9}\]</span></span></p>
<p>정규분포에서 산포 모수가 분산 <span class="math inline">\(\phi=\sigma^2\)</span> 이므로 척도화 편차는 잔차제곱합 <span class="math inline">\(D^*(\pmb y;\hat {\pmb \mu}) = SSE\)</span> 가 되며 이항분포에서는 편차와 척도화 편차가 같다.</p>
<p>이제 다시 o-ring 의 예제(<a href="#sec-oring" class="quarto-xref"><span>섹션&nbsp;5.2.1</span></a>)에 대한 로지스틱 회귀식의ㅣ 결과를 보자.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(damage, 6 - damage) ~ temp, family = binomial, 
    data = orings)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) 11.66299    3.29626   3.538 0.000403 ***
temp        -0.21623    0.05318  -4.066 4.78e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 38.898  on 22  degrees of freedom
Residual deviance: 16.912  on 21  degrees of freedom
AIC: 33.675

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>마지막에 <code>Residual deviance</code> 는 다음과 같이 절편과 하나의 예측 변수(온도)를 포함한 회귀식에 대한 편차의 값과 자유도를 나타내는 것이다.</p>
<p><span class="math display">\[
\log \left [ \frac{P(y=1|x)}{1-P(y=1|x)} \right ] =\beta_0 + \beta_1 x \quad \rightarrow D(\pmb y;\hat {\pmb \mu}) = 16.9122785
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">deviance</span>(logit1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.91228</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">df.residual</span>(logit1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21</code></pre>
</div>
</div>
<p>위에서 언급하였듯이 모형이 옪다는 가정하에서 편차 <span class="math inline">\(D(\pmb y;\hat {\pmb \mu})\)</span> 는 자유도가 21 인 <span class="math inline">\(\chi^2\)</span>-분포를 따르므로 아래에서 구한 <span class="math inline">\(P(\chi^2 \ge 16.9122785 )\)</span> 가 크게 나오는 것은 모형이 적절하다는 의미이다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fu">deviance</span>(logit1), <span class="fu">df.residual</span>(logit1),<span class="at">lower=</span><span class="cn">FALSE</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7164099</code></pre>
</div>
</div>
<p>또한 <code>Null deviance</code> 는 다음과 같이 절편만 포함한 회귀식에 대한 편차의 값과 자유도를 나타내는 것이다.</p>
<p><span class="math display">\[
\log \left [ \frac{P(y=1|x)}{1-P(y=1|x)} \right ] =\beta_0
\]</span></p>
</section>
<section id="검정과-모형의-선택" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="검정과-모형의-선택"><span class="header-section-number">5.4.3</span> 검정과 모형의 선택</h3>
<p>로지스틱 회귀모형에서 하나의 회귀 계수가 유의한 지에 대한 다음 검정은</p>
<p><span class="math display">\[ H_0 : \beta_i =0 \quad vs. \quad H_1: \beta_i \ne 0 \]</span> 다음과 같은 표준화된 통계량을 이용하여 정규분포 검정을적용할 수 있다.</p>
<p><span class="math display">\[ z = \frac{ \hat \beta_i}{SE(\hat \beta_i)} \]</span> 또한 회귀 계수 <span class="math inline">\(\beta_i\)</span> 에 대한 <span class="math inline">\((1-\alpha)100\%\)</span> 신뢰구간은 다음과 같이 구할 수 있다.</p>
<p><span class="math display">\[  [ \hat \beta_i - z_{\alpha/2 } SE(\hat \beta_i) , `` \hat \beta_i + z_{\alpha/2 } SE(\hat \beta_i) ] \]</span></p>
<p>위의 o-ring 예제(<a href="#sec-oring" class="quarto-xref"><span>섹션&nbsp;5.2.1</span></a>)에서 온도에 대한 회귀 계수의 <span class="math inline">\(95\%\)</span> 신뢰구간은 다음과 같이 <code>MASS</code> 패키지의 함수 <code>confint</code>를 이용해서 구한다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(logit1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %    97.5 %
(Intercept)  5.575195 18.737598
temp        -0.332657 -0.120179</code></pre>
</div>
</div>
<p>이제 회귀모형에서 고려하는 다음과 같은 가설 검정을 고려해 보자.</p>
<p><span id="eq-glmhypo"><span class="math display">\[ H_0 : \text{ reduced model} \quad vs. \quad H_1: \text{full model}  \tag{5.10}\]</span></span></p>
<p>로지스틱 회귀에서 편차(deviance)의 차이를 이용하여 두 개의 모형 중 하나를 선택하는 방법을 살펴보자.</p>
<p>다음과 같이 서로 다른 모형과 그에 대한 가설을 생각해 보자. <span class="math display">\[
H_0: g[p(x)]  = {\pmb x}_1^t {\pmb \beta}_1 \quad \text{vs.} \quad H_1: g[p(x)] = {\pmb x_1}^t {\pmb \beta}_1+ {\pmb x}_2^t {\pmb \beta}_2
\]</span></p>
<p>가설을 달리 표현하면 다음과 같이 쓸 수 있다.</p>
<p><span class="math display">\[
H_0: {\pmb \beta}_2 =0  \quad \text{vs.} \quad H_1: {\pmb \beta}_2 \ne 0
\]</span> 위의 가설에서 <span class="math inline">\(dim(\pmb \beta_1) = p\)</span>, <span class="math inline">\(dim(\pmb \beta_2) = q\)</span> 라고 하면 대립가설 <span class="math inline">\(H_1\)</span>의 모형이 귀무가설 <span class="math inline">\(H_0\)</span>의 모형보다 큰 모형이다.</p>
<p>만약 축소모형(reduced moldel, <span class="math inline">\(H_0\)</span>)에 대한 잔차 편차(Residual Deviance)를 <span class="math inline">\(D_0\)</span> 라고 하고 큰 모형(full model, <span class="math inline">\(H_1\)</span>)에 대한 잔차 편차를 <span class="math inline">\(D_1\)</span> 라고 하면 귀무가설이 참인 경우 두 편차의 차이 <span class="math inline">\(D_0 - D_1\)</span> 은 근사적으로 자유도가 <span class="math inline">\(q\)</span> 인 카이제곱분포를 따른다. 여기서 자유도 <span class="math inline">\(q\)</span> 는 두 모형의 회귀계수의 갯수 차이 $(p+q)-p=q이다. 이러한 두 편차의 차이의 점근적 분포 가능도비검정 이론에 의하여 유도할 수 있다.</p>
<p><span class="math display">\[ D= D_0 - D_1 \]</span></p>
<p>두 모형에 대한 모수의 개수의 차이 <span class="math inline">\(q\)</span>인 경우 귀무가설이 참일 때 deviance의 차인 <span class="math inline">\(D= D_0 - D_1\)</span> 통계량은 자유도가 <span class="math inline">\(q\)</span>인 <span class="math inline">\(\chi^2\)</span>-분포를 따른다. 따라서 유의수준 <span class="math inline">\(\alpha\)</span>에서 <span class="math inline">\(D\)</span> 통계량이 <span class="math inline">\(\chi^2_\alpha(q)\)</span>보다 크면 귀무가설을 기각한다.</p>
<p>편차 차이를 이용하여 검정하는방법은 가능도비 검정(likelihood ratio test)과 동일한 검정이다.</p>
<p>다음 자료는27명의 암환자들에 대한 암의 호전(remission of cancer)이며 종속변수 <span class="math inline">\(y\)</span>는 <strong>remiss</strong>로 1이면 암이 호전되었다는 표시이다. 나머지 6개의 변수는 환자의 특성을 나타내는 독립변수이다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>cancer <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"remission.txt"</span>,<span class="at">header=</span>T, <span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>cancer <span class="sc">%&gt;%</span> <span class="fu">kbl</span>() <span class="sc">%&gt;%</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>( <span class="at">full_width =</span> F)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">id</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">remiss</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">cell</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">smear</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">infil</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">li</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">blast</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">temp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">1.100</td>
<td style="text-align: right;">0.996</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: right;">0.740</td>
<td style="text-align: right;">0.992</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">0.88</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.176</td>
<td style="text-align: right;">0.982</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">1.053</td>
<td style="text-align: right;">0.986</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">0.68</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">0.519</td>
<td style="text-align: right;">0.980</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">0.519</td>
<td style="text-align: right;">0.982</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">0.92</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">1.230</td>
<td style="text-align: right;">0.992</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">1.354</td>
<td style="text-align: right;">1.020</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.322</td>
<td style="text-align: right;">0.999</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.038</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">0.279</td>
<td style="text-align: right;">0.988</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right;">0.146</td>
<td style="text-align: right;">0.982</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.380</td>
<td style="text-align: right;">1.006</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.39</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.8</td>
<td style="text-align: right;">0.114</td>
<td style="text-align: right;">0.990</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">1.037</td>
<td style="text-align: right;">0.990</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">2.064</td>
<td style="text-align: right;">1.020</td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">0.42</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.114</td>
<td style="text-align: right;">1.014</td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">1.322</td>
<td style="text-align: right;">1.004</td>
</tr>
<tr class="odd">
<td style="text-align: right;">19</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.44</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">0.114</td>
<td style="text-align: right;">0.990</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: right;">0.63</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">1.072</td>
<td style="text-align: right;">0.986</td>
</tr>
<tr class="odd">
<td style="text-align: right;">21</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.176</td>
<td style="text-align: right;">1.010</td>
</tr>
<tr class="even">
<td style="text-align: right;">22</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">0.93</td>
<td style="text-align: right;">0.84</td>
<td style="text-align: right;">0.6</td>
<td style="text-align: right;">1.591</td>
<td style="text-align: right;">1.020</td>
</tr>
<tr class="odd">
<td style="text-align: right;">23</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.58</td>
<td style="text-align: right;">0.58</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0.531</td>
<td style="text-align: right;">1.002</td>
</tr>
<tr class="even">
<td style="text-align: right;">24</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.32</td>
<td style="text-align: right;">0.30</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">0.886</td>
<td style="text-align: right;">0.988</td>
</tr>
<tr class="odd">
<td style="text-align: right;">25</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">1.7</td>
<td style="text-align: right;">0.964</td>
<td style="text-align: right;">0.990</td>
</tr>
<tr class="even">
<td style="text-align: right;">26</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.69</td>
<td style="text-align: right;">0.69</td>
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">0.398</td>
<td style="text-align: right;">0.986</td>
</tr>
<tr class="odd">
<td style="text-align: right;">27</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: right;">0.7</td>
<td style="text-align: right;">0.398</td>
<td style="text-align: right;">0.986</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>다음은 6개의 독립변수를 모두 적합한 완전모형(full model)의 추정 결과이다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>logit3_L <span class="ot">&lt;-</span> <span class="fu">glm</span>(remiss<span class="sc">~</span>cell <span class="sc">+</span> smear <span class="sc">+</span> infil <span class="sc">+</span> li <span class="sc">+</span> blast <span class="sc">+</span> temp,<span class="at">family=</span>binomial,<span class="at">data=</span>cancer)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit3_L)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = remiss ~ cell + smear + infil + li + blast + temp, 
    family = binomial, data = cancer)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)  58.0385    71.2364   0.815   0.4152  
cell         24.6615    47.8377   0.516   0.6062  
smear        19.2936    57.9500   0.333   0.7392  
infil       -19.6013    61.6815  -0.318   0.7507  
li            3.8960     2.3371   1.667   0.0955 .
blast         0.1511     2.2786   0.066   0.9471  
temp        -87.4339    67.5735  -1.294   0.1957  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 34.372  on 26  degrees of freedom
Residual deviance: 21.751  on 20  degrees of freedom
AIC: 35.751

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<p>위의 회귀분석 결과를 보면 변수들 중 세 개의 변수 <code>li</code>, <code>temp</code> , <code>cell</code> 만 포함한 축소된 모형(reduced model)을 생각해보자.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>logit3_S <span class="ot">&lt;-</span> <span class="fu">glm</span>(remiss<span class="sc">~</span>cell <span class="sc">+</span> li <span class="sc">+</span> temp,<span class="at">family=</span>binomial,<span class="at">data=</span>cancer)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit3_S)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = remiss ~ cell + li + temp, family = binomial, data = cancer)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)   67.634     56.888   1.189   0.2345  
cell           9.652      7.751   1.245   0.2130  
li             3.867      1.778   2.175   0.0297 *
temp         -82.074     61.712  -1.330   0.1835  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 34.372  on 26  degrees of freedom
Residual deviance: 21.953  on 23  degrees of freedom
AIC: 29.953

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
<p>위에서 적합한 두개의 모형이 유의한 차이가 있는지 위에서 논의한 편차의 차이를 이용하여 검정해 보자. 다음과 같은 가설을 검정하는 검정은 다음과 같이 <code>anova</code>함수로 수행할 수 있다.</p>
<p>앞에서 두 모형을 적합한 결과에서 잔차 편차(Residual deviance)의 차이를 이용하여 검정을 실시하였다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(logit3_S, logit3_L,<span class="at">test=</span><span class="st">"Chisq"</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: remiss ~ cell + li + temp
Model 2: remiss ~ cell + smear + infil + li + blast + temp
  Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
1        23     21.953                     
2        20     21.751  3  0.20272   0.9771</code></pre>
</div>
</div>
<p>위의 <code>anova</code> 함수의 결과를 보면 p-vlaue가 0.9771497로 매우 크며 귀무가설 <span class="math inline">\(H_0\)</span>를 기각하지 못한다. 따라서 3개의 독립변수만 가진 축소된 모형을 선택할 수 있다.</p>
<p>다시 하나의 독립변수 <code>li</code> 만 가지는 축소모형을 고려해 보자.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>logit3_S2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(remiss<span class="sc">~</span>li,<span class="at">family=</span>binomial,<span class="at">data=</span>cancer)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit3_S2)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = remiss ~ li, family = binomial, data = cancer)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)   -3.777      1.379  -2.740  0.00615 **
li             2.897      1.187   2.441  0.01464 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 34.372  on 26  degrees of freedom
Residual deviance: 26.073  on 25  degrees of freedom
AIC: 30.073

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>완전모형과의 차이에 대한검정을 실시하며 다음과 같은 결과가 나오고 cencer remission 자료는 사실상 변수 <code>li</code>만으로도 충분히 설명할 수 있다는 결론이다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(logit3_S2, logit3_L,<span class="at">test=</span><span class="st">"Chisq"</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: remiss ~ li
Model 2: remiss ~ cell + smear + infil + li + blast + temp
  Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
1        25     26.073                     
2        20     21.751  5   4.3223    0.504</code></pre>
</div>
</div>
<p>모형을 선택하는 경우 AIC(Akaike Information Criteria)를 자주 이용한다. AIC는 다음과 같이 정의되며</p>
<p><span class="math display">\[ AIC = -2*log(\text{Likelihood}) +2*(\text{number of parameter}) \]</span> 모형의 AIC값이 작을수록 좋은 모형이다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(logit3_L, logit3_S, logit3_S2)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          df      AIC
logit3_L   7 35.75065
logit3_S   4 29.95337
logit3_S2  2 30.07296</code></pre>
</div>
</div>
<p>위에서 나타난 AIC로 모형을 선택한다면 독립변수가 3개(<code>li</code>, <code>temp</code> , <code>cell</code> )인 모형이 가장 좋은 모형이다. AIC는 모형에 위에서 주어진 두 번째 항에서 독립변수의 수(number of parameter)를 더해주므로 모형이 복잡할수록 그 값이 증가하여 모형의 선택에서 벌칙(penalty)를 주는 것으로 이해할 수 있다.</p>
<p>AIC는 로그우도함수와 모형의 자유도로 직접 계산할 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(logit3_S)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 29.95337</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># value of log likelihood</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">as.numeric</span>(<span class="fu">logLik</span>(logit3_S))</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -10.97668</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#number of parameter = 3+1</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">attr</span>(<span class="fu">logLik</span>(logit3_S),<span class="st">"df"</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#AIC</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="dv">2</span><span class="sc">*</span><span class="fu">as.numeric</span>(<span class="fu">logLik</span>(logit3_S))<span class="sc">+</span><span class="dv">2</span><span class="sc">*</span><span class="fu">attr</span>(<span class="fu">logLik</span>(logit3_S),<span class="st">"df"</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 29.95337</code></pre>
</div>
</div>
<p>위에서 모형의 자유도는 독립변수의 개수 3개와 절편 1개를 더해서 4개가 된다.</p>
</section>
<section id="적합도-검정" class="level3" data-number="5.4.4">
<h3 data-number="5.4.4" class="anchored" data-anchor-id="적합도-검정"><span class="header-section-number">5.4.4</span> 적합도 검정</h3>
<p>모형의 적합도를 측정하는 통계량으로 편차(deviance)뿐만 아니라 <span class="math inline">\(\chi^2\)</span>-통계량도 매우 유용하다. <span class="math inline">\(\chi^2\)</span>-통계량은 다음과 같이 주어진다.</p>
<p><span id="eq-chisquare"><span class="math display">\[ \chi^2 = \sum_{i=1}^n \frac{ (y_i - m_i \hat p(x_i))^2 }{m_i \hat p(x_i)[1-\hat p(x_i)]}  \tag{5.11}\]</span></span></p>
<p>위의 식은 다음과 같은 표준화된 피어슨 잔차 <span class="math inline">\(r_i\)</span> 의 제곱합과 같다.</p>
<p><span class="math display">\[ r_i = \frac{ y_i - m_i \hat p(x_i)}{\sqrt{var(\hat y_i)}} \]</span> 자료의 수가 많으면 <span class="math inline">\(\chi^2\)</span>-통계량은 <span class="math inline">\(\chi^2\)</span> 분포를 따른다.</p>
<p><span class="math inline">\(\chi^2\)</span>-통계량은 다음과 같이 계산할 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">residuals</span>(logit1,<span class="at">type=</span><span class="st">"pearson"</span>)<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28.06738</code></pre>
</div>
</div>
</section>
</section>
<section id="과산포" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="과산포"><span class="header-section-number">5.5</span> 과산포</h2>
<section id="과산포의-개요" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="과산포의-개요"><span class="header-section-number">5.5.1</span> 과산포의 개요</h3>
<p>로지스틱 회귀식을 적합한 뒤에 주어진 모형이 적절한 모형이라고 판단되지만 잔차 편차(residual devince) <span class="math inline">\(D\)</span>가 기대 이상으로 너무 커서 서로 상충되는 결론이 나오면 다음과 같은 원인을 의심할 수 있다.</p>
<ul>
<li><p>중요한 예측변수 <span class="math inline">\(x\)</span>가 모형에 포함되지 않았거나 예측함수 <span class="math inline">\(\eta={\pmb x}^t {\pmb \beta}\)</span>가 잘못 설정된 경우</p></li>
<li><p>이상점(outlier)이 있는 경우</p></li>
<li><p>반복수의 수가 매우 적은 경우</p></li>
<li><p>분포의 가정이 맞지 않는 경우 - 독립이 아닌 경우, 군집효과(cluster effect)</p></li>
</ul>
<p>반응변수 <span class="math inline">\(y\)</span>가 이항분포 <span class="math inline">\(B(m,p)\)</span> 를 따르면 그 평균과 분산은 다음과 같이 주어진다.</p>
<p><span class="math display">\[ E(y) = mp \quad \text{ and } \quad Var(y) = mp(1-p) \]</span></p>
<p>자료의 확률 구조가 이항분포의 평균과 분산에 대한 가정과 맞지 않는 경우를 분산의 크기에 따라 과산포(overdispersion) 또는 underdispersion이라고 한다.</p>
<ul>
<li><p>overdispersion if <span class="math inline">\(Var(y) &gt; mp(1-p)\)</span></p></li>
<li><p>underdispersion if <span class="math inline">\(Var(y) &lt; mp(1-p)\)</span></p></li>
</ul>
<p>예를 들어 모집단이 몇 개의 군집으로 이루져 있다면 군집효과로 발생한 성질때문에 관측치의 분산이 이항분포의 분산보다 큰 경우가 생기게 된다. 이러한 경우를 overdispersion이라고 한다.</p>
<p>군집 효과는 다음과 같은 이유로 발생할 수 있다.</p>
<ul>
<li>군집간 의 분포가 서로 다른 경우</li>
<li>관측값이 서로 독립이 아닌 경우</li>
</ul>
<p>표본의 개수를 <span class="math inline">\(n\)</span>이라고 하고 군집의 크기를 <span class="math inline">\(k\)</span> 라 하면 군집의 개수는 <span class="math inline">\(l=n/k\)</span> 이 된다.</p>
<ul>
<li><p><span class="math inline">\(i\)</span>번째 군집에서 성공의 회수 <span class="math inline">\(z_i\)</span>는 이항분포 <span class="math inline">\(B(k,p_i)\)</span>를 따른다고 하자.</p></li>
<li><p>이 때, 성공의 확률 <span class="math inline">\(p_i\)</span>를 평균이 <span class="math inline">\(E(p_i)=p\)</span>이고 분산이 <span class="math inline">\(Var(p_i)=\tau^2 p(1-p)\)</span>인 확률변수라고 가정하자.</p>
<p>이제 총 성공의 횟수 <span class="math inline">\(y =z_1+\dots+z_k\)</span>의 분포를 살펴보면</p></li>
</ul>
<p><span class="math display">\[ E(y) = \sum_i E(Z_i) = \sum_i kp= mp \]</span></p>
<p>로서 평균은 보통의 경우와 같지만 분산은 다음과 같이 overidspersion이 나타난다.</p>
<p><span class="math display">\[\begin{align*}
Var(y) &amp; = \sum_i Var(z_i) \\
  &amp;= \sum_i \left [ E(Var(z_i|p_i)) + Var(E(z_i|p_i) \right ] \\
  &amp;= \sum_i \left [ E kp_i(1-p_i) + Var(kp_i) \right ] \\
  &amp; = \sum_i \left [ kE(p_i) - kE(p_i^2) + k^2\tau^2 p(1-p) \right ] \\
  &amp; = \sum_i \left [ kp - k\{ \tau^2 p(1-p) + p^2\}  + k^2\tau^2 p(1-p) \right ] \\
  &amp; = \sum_i \left [ kp - k\{ \tau^2 p(1-p) + p^2\}  + k^2\tau^2 p(1-p) \right ] \\
   &amp; = [1+\tau^2(k-1)]kp(1-p)
\end{align*}\]</span></p>
<p>즉 <span class="math inline">\(1+\tau^2(k-1)\)</span>의 값이 1보다 크기 때문에 반응변수가 독립인 경우의 분산 <span class="math inline">\(kp(1-p)\)</span>보다 커진다. <span class="math inline">\(1+\tau^2(k-1)\)</span> 의 값을 산포모수(dispersion parameter) 라고 부른다.</p>
<div class="callout callout-style-default callout-important callout-titled" title="산포모수">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
산포모수
</div>
</div>
<div class="callout-body-container callout-body">
<p>이항변수에 대한 로지스틱회위에서 다음과 같이 분산이 이항분포의 이론적 분산 <span class="math inline">\(kp(1-p)\)</span> 보다 크게 크게 나타나는 경우 그 계수를 산포모수(dispersion parameter, <span class="math inline">\(\sigma^2\)</span>) 이라고 부른다.</p>
<p><span class="math display">\[Var(y) = \sigma^2 mp(1-p) &gt; kp(1-p)\]</span> 산포모수(<span class="math inline">\(\sigma^2\)</span>)는 과산포가 없으면 1 이고 과산포가 존재하면 1 보다 큰 값을 가진다.</p>
</div>
</div>
<p>산포모수는 식 <a href="#eq-chisquare" class="quarto-xref">식&nbsp;<span>5.11</span></a> 에 주어진 <span class="math inline">\(\chi^2\)</span>-통계량에 의해 추정될 수 있다.</p>
<p><span class="math display">\[ \hat \sigma^2 = \chi^2/(n-p) \]</span> 주의할 점은 overidspersion이 있다 하더라도 회귀계수의 추정치 <span class="math inline">\(\beta\)</span>의 추정에는 영향을 미치지 않는다.</p>
<p>위와 같이 overidspersion이 있다고 판단되는 경우에는 추가로 산포모수(dispersion parameter) <span class="math inline">\(\sigma^2\)</span>를 고려하고 이를 추정하여 회귀계수 <span class="math inline">\(\beta\)</span>의 분산 계산 시 다음과 같이 추가해서 계산한다.</p>
<p><span class="math display">\[ Var(\hat {\pmb \beta}) = \hat \sigma^2(X'\hat W X)^{-1} \]</span></p>
</section>
<section id="예제-1" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="예제-1"><span class="header-section-number">5.5.2</span> 예제</h3>
<p>부교재 <span class="citation" data-cites="faraway2016ext">Faraway (<a href="../references.html#ref-faraway2016ext" role="doc-biblioref">2016</a>)</span> 의 2.11 절에 소개된 자료를 이용하여 과산포에 대한 예제를 살펴보자.</p>
<p>데이터 <code>trouegg</code> 는 5개의 장소와 4개의 시번에서 관측한 송어(trout) 알의 생존에 대한 자료이다. 데이터를 구성하는 변수의 이름과 의미는 다음과 같다.</p>
<ul>
<li><code>survive</code>: the number of surviving eggs</li>
<li><code>total</code>: the number of eggs in the box</li>
<li><code>location</code> : the location in the stream with levels 1 2 3 4 5</li>
<li><code>period</code> : the number of weeks after placement that the box was withdrawn levels 4 7 8 11</li>
</ul>
<p>다음은 데이터 <code>trouegg</code> 이다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>troutegg <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">arrange</span>(location, period) <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">relocate</span>(<span class="st">`</span><span class="at">location</span><span class="st">`</span>, <span class="st">`</span><span class="at">period</span><span class="st">`</span>, <span class="st">`</span><span class="at">survive</span><span class="st">`</span>, <span class="st">`</span><span class="at">total</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">kbl</span>() <span class="sc">%&gt;%</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>( <span class="at">full_width =</span> F)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">location</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">period</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">survive</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">4</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">94</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">7</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">98</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">8</td>
<td style="text-align: right;">77</td>
<td style="text-align: right;">86</td>
</tr>
<tr class="even">
<td style="text-align: left;">16</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">11</td>
<td style="text-align: right;">141</td>
<td style="text-align: right;">155</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">4</td>
<td style="text-align: right;">106</td>
<td style="text-align: right;">108</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">7</td>
<td style="text-align: right;">91</td>
<td style="text-align: right;">106</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">8</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">96</td>
</tr>
<tr class="even">
<td style="text-align: left;">17</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">11</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">122</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">4</td>
<td style="text-align: right;">119</td>
<td style="text-align: right;">123</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">7</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">130</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">8</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">119</td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">11</td>
<td style="text-align: right;">91</td>
<td style="text-align: right;">125</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">4</td>
<td style="text-align: right;">104</td>
<td style="text-align: right;">104</td>
</tr>
<tr class="even">
<td style="text-align: left;">9</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">7</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">97</td>
</tr>
<tr class="odd">
<td style="text-align: left;">14</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">8</td>
<td style="text-align: right;">67</td>
<td style="text-align: right;">99</td>
</tr>
<tr class="even">
<td style="text-align: left;">19</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">11</td>
<td style="text-align: right;">111</td>
<td style="text-align: right;">132</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">4</td>
<td style="text-align: right;">49</td>
<td style="text-align: right;">93</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">7</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">113</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">8</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">88</td>
</tr>
<tr class="even">
<td style="text-align: left;">20</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">11</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">138</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(troutegg)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    survive           total        location period
 Min.   :  0.00   Min.   : 86.00   1:4      4 :5  
 1st Qu.: 74.50   1st Qu.: 96.75   2:4      7 :5  
 Median : 90.00   Median :107.00   3:4      8 :5  
 Mean   : 81.35   Mean   :111.30   4:4      11:5  
 3rd Qu.:104.00   3rd Qu.:123.50   5:4            
 Max.   :141.00   Max.   :155.00                  </code></pre>
</div>
</div>
<p>이제 자료 <code>troutegg</code> 에 로지스틱 회귀식을 다음과 같이 적합해보자.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>bmod <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(survive,total<span class="sc">-</span>survive) <span class="sc">~</span>      location<span class="sc">+</span>period,         <span class="at">family=</span>binomial,troutegg)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bmod)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(survive, total - survive) ~ location + period, 
    family = binomial, data = troutegg)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)   4.6358     0.2813  16.479  &lt; 2e-16 ***
location2    -0.4168     0.2461  -1.694   0.0903 .  
location3    -1.2421     0.2194  -5.660 1.51e-08 ***
location4    -0.9509     0.2288  -4.157 3.23e-05 ***
location5    -4.6138     0.2502 -18.439  &lt; 2e-16 ***
period7      -2.1702     0.2384  -9.103  &lt; 2e-16 ***
period8      -2.3256     0.2429  -9.573  &lt; 2e-16 ***
period11     -2.4500     0.2341 -10.466  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1021.469  on 19  degrees of freedom
Residual deviance:   64.495  on 12  degrees of freedom
AIC: 157.03

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
<p>앞의 예제와 같이 결과의 잔차 편차가 <span class="math inline">\(\chi^2\)</span>-분포를 기준으로 얼마나 큰지 살펴보자.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pchisq</span>(<span class="fu">deviance</span>(bmod), <span class="fu">df.residual</span>(bmod),<span class="at">lower=</span><span class="cn">FALSE</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.379416e-09</code></pre>
</div>
</div>
<p>잔차 편차가 매우 큰 것을 알 수 있으며 산포모수 <span class="math inline">\(\sigma^2\)</span> 는 식 <a href="#eq-chisquare" class="quarto-xref">식&nbsp;<span>5.11</span></a> 에 주어진 것 처럼 다음과 같이 추정될 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>sigma2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">residuals</span>(bmod,<span class="at">type=</span><span class="st">"pearson"</span>)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span><span class="dv">12</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>sigma2</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.330322</code></pre>
</div>
</div>
<p>위에서 구한 산포 모수가 크다는 것은 다음과 같이 o-ring 자료에 대한 로지스틱 회귀의 산포 모수와 비교하면 알 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>sigma2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">residuals</span>(logit1,<span class="at">type=</span><span class="st">"pearson"</span>)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span><span class="dv">21</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>sigma2</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.336542</code></pre>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-faraway2016ext" class="csl-entry" role="listitem">
Faraway, Julian J. 2016. <em>Extending the linear model with R: generalized linear, mixed effects and nonparametric regression models</em>. CRC press.
</div>
<div id="ref-weisberg4" class="csl-entry" role="listitem">
Weisberg, Sanford. 2014. <em>Applied Linear Regression</em>. Fourth. Hoboken <span>NJ</span>: Wiley. <a href="http://z.umn.edu/alr4ed">http://z.umn.edu/alr4ed</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "복사완료!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "복사완료!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    const typesetMath = (el) => {
      if (window.MathJax) {
        // MathJax Typeset
        window.MathJax.typeset([el]);
      } else if (window.katex) {
        // KaTeX Render
        var mathElements = el.getElementsByClassName("math");
        var macros = [];
        for (var i = 0; i < mathElements.length; i++) {
          var texText = mathElements[i].firstChild;
          if (mathElements[i].tagName == "SPAN") {
            window.katex.render(texText.data, mathElements[i], {
              displayMode: mathElements[i].classList.contains('display'),
              throwOnError: false,
              macros: macros,
              fleqn: false
            });
          }
        }
      }
    }
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        for (let i = 0; i < 2; i++) {
          container.appendChild(note.children[i].cloneNode(true));
        }
        typesetMath(container);
        return container.innerHTML
      } else {
        typesetMath(note);
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      typesetMath(note);
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../notes/diagnose.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">진단의 평가</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../notes/poisson.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">포아송 회귀모형</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>