<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.510">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>데이터 분석 방법론 - 7&nbsp; 반복측정자료</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../notes/spline-01.html" rel="next">
<link href="../notes/poisson.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<script type="text/javascript">
 window.MathJax = {
  tex: {
    macros: {
    RR: '{\\mathbb R}',                    // a simple string replacement
    hatmat:'{\\pmb X ({\\pmb X}^t {\\pmb X} )^{-1} {\\pmb X}^t}',
    bold: ['\\boldsymbol{#1}',1] ,     // this macro has one parameter
    pardiff: ['\\frac{\\partial#2}{\\partial#1}', 2, 'x'], // this macro has an optional parameter that defaults to 'x'
    pardifftwo: ['\\frac{\\partial#1}{\\partial#2}', 2]
  },
  environments: {
  braced: ["\\left\\{", "\\right\\}"]
  }
 }
};
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notes/random_effect.html">혼합모형</a></li><li class="breadcrumb-item"><a href="../notes/random_effect.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">반복측정자료</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="사이드바 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">데이터 분석 방법론</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/ilovedata/statmehods" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../데이터-분석-방법론.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="검색"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">서론</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">분할표의 분석</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/association.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">연관성의 측도</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/association-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">연관성의 검정</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/diagnose.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">진단의 평가</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">일반화 선형모형</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">로지스틱 회귀모형</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/poisson.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">포아송 회귀모형</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">혼합모형</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/random_effect.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">반복측정자료</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">비모수 회귀모형</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/spline-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">국소 회귀모형</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/spline-02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">스플라인 회귀모형</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/survival-01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">생존함수와 위험함수</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">실습</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="토글 섹션">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/logistic_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">로지스틱 회귀모형 실습 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/logistic_practice_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">로지스틱 회귀모형 실습 2</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/lme_practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">반복측정자료 실습 1</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../notes/lme_practice_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">반복측정자료 실습 2</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#필요한-패키지와-함수" id="toc-필요한-패키지와-함수" class="nav-link active" data-scroll-target="#필요한-패키지와-함수"><span class="header-section-number">7.1</span> 필요한 패키지와 함수</a></li>
  <li><a href="#repeatmeasure-paired" id="toc-repeatmeasure-paired" class="nav-link" data-scroll-target="#repeatmeasure-paired"><span class="header-section-number">7.2</span> 독립표본과 대응표본</a></li>
  <li><a href="#임의효과" id="toc-임의효과" class="nav-link" data-scroll-target="#임의효과"><span class="header-section-number">7.3</span> 임의효과</a></li>
  <li><a href="#repeatmeasure-oneway" id="toc-repeatmeasure-oneway" class="nav-link" data-scroll-target="#repeatmeasure-oneway"><span class="header-section-number">7.4</span> 일원배치 모형</a>
  <ul class="collapse">
  <li><a href="#고정효과-모형" id="toc-고정효과-모형" class="nav-link" data-scroll-target="#고정효과-모형"><span class="header-section-number">7.4.1</span> 고정효과 모형</a></li>
  <li><a href="#임의효과-모형" id="toc-임의효과-모형" class="nav-link" data-scroll-target="#임의효과-모형"><span class="header-section-number">7.4.2</span> 임의효과 모형</a></li>
  </ul></li>
  <li><a href="#반복측정자료" id="toc-반복측정자료" class="nav-link" data-scroll-target="#반복측정자료"><span class="header-section-number">7.5</span> 반복측정자료</a>
  <ul class="collapse">
  <li><a href="#선형-회귀모형" id="toc-선형-회귀모형" class="nav-link" data-scroll-target="#선형-회귀모형"><span class="header-section-number">7.5.1</span> 선형 회귀모형</a></li>
  <li><a href="#임의계수-모형" id="toc-임의계수-모형" class="nav-link" data-scroll-target="#임의계수-모형"><span class="header-section-number">7.5.2</span> 임의계수 모형</a></li>
  <li><a href="#혼합효과-모형" id="toc-혼합효과-모형" class="nav-link" data-scroll-target="#혼합효과-모형"><span class="header-section-number">7.5.3</span> 혼합효과 모형</a></li>
  <li><a href="#선형혼합모형의-적합" id="toc-선형혼합모형의-적합" class="nav-link" data-scroll-target="#선형혼합모형의-적합"><span class="header-section-number">7.5.4</span> 선형혼합모형의 적합</a></li>
  <li><a href="#임의효과에-대한-예측" id="toc-임의효과에-대한-예측" class="nav-link" data-scroll-target="#임의효과에-대한-예측"><span class="header-section-number">7.5.5</span> 임의효과에 대한 예측</a></li>
  <li><a href="#수축-현상" id="toc-수축-현상" class="nav-link" data-scroll-target="#수축-현상"><span class="header-section-number">7.5.6</span> 수축 현상</a></li>
  <li><a href="#모형의-비교" id="toc-모형의-비교" class="nav-link" data-scroll-target="#모형의-비교"><span class="header-section-number">7.5.7</span> 모형의 비교</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../notes/random_effect.html">혼합모형</a></li><li class="breadcrumb-item"><a href="../notes/random_effect.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">반복측정자료</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="repeat" class="quarto-section-identifier"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">반복측정자료</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="필요한-패키지와-함수" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="필요한-패키지와-함수"><span class="header-section-number">7.1</span> 필요한 패키지와 함수</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(faraway)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(alr4)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(brms)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># ggplot2 에서 한글의 사용</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(showtext)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="fu">font_add_google</span>(<span class="st">"Nanum Pen Script"</span>, <span class="st">"nanum"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">showtext_auto</span>()</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="repeatmeasure-paired" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="repeatmeasure-paired"><span class="header-section-number">7.2</span> 독립표본과 대응표본</h2>
<p>서로 다른 두 처리의 효과(treatment effect)를 비교하기 위하여 주로 사용되는 방법은 두 개의 독립표본(independent sample)을 비교하는 t-검정법이다. 서로 독립인 두개의 집단(구성원이 겹치지 않는 집단)에 서로 다른 처리를 적용한 뒤에 관측된 자료의 표본 평균을 비교하여 두 개의 처리 효과의 차이를 통계적으로 검정하는 방법이다. t-검정을 위한 분포 가정은 다음과 같다.</p>
<p><span class="math display">\[
x_1,x_2, \dots x_{n} \sim_{iid} N(\mu_1, \sigma^2)
\quad
y_1,y_2, \dots y_{n} \sim_{iid} N(\mu_2, \sigma^2)
\]</span></p>
<p>위의 가정을 다음과 같은 평균모형(mean model)로 표현할 수 있다.</p>
<p><span id="eq-meanmodel"><span class="math display">\[
x_i = \mu_1 + e_{i1}, \quad y_i = \mu_2 + e_{i2}  
\tag{7.1}\]</span></span></p>
<p>여기서 <span class="math inline">\(e_{i1}\)</span>와 <span class="math inline">\(e_{i2}\)</span>들은 모두 독립이며 <span class="math inline">\(N(0,\sigma^2)\)</span>을 따르는 오차들이다.</p>
<p>여기서 확률변수 <span class="math inline">\(x\)</span>와 <span class="math inline">\(y\)</span>는 서로 독립이고 각 관측값 <span class="math inline">\(x_1,x_2, \dots x_{n_1}\)</span>과 <span class="math inline">\(y_1,y_2, \dots y_{n_2}\)</span>들도 각각 모두 독립이다. 분포가정에서 다른 것은 확률변수 <span class="math inline">\(x\)</span>와 <span class="math inline">\(y\)</span>의 평균이 다르다.</p>
<p>이러한 가정 하에서 다음의 두개의 가설검정을 할 수 있는 방법이 t-검정법이며</p>
<p><span id="eq-hypo"><span class="math display">\[
H_0 : \mu_1 = \mu_2 \quad \text{vesus} \quad H_1 : \mu_1 \ne \mu_2  
\tag{7.2}\]</span></span></p>
<p>검정통계량은 다음과 같이 주어진다.</p>
<p><span id="eq-tvalue1"><span class="math display">\[
t = \frac{ \bar x -\bar y} {s_p \sqrt{\tfrac{1}{n} + \tfrac{1}{n}}}  
\tag{7.3}\]</span></span></p>
<p>여기서 <span class="math inline">\(\bar x\)</span>와 <span class="math inline">\(\bar y\)</span>는 각 집단의 표본 평균이고 <span class="math inline">\(s_p^2\)</span>은 합동분산추정량(pooled variance estimator)이다.</p>
<p><span class="math display">\[
s^2_p = \frac{\sum_{i=1}^n (x_i -\bar x)^2 + \sum_{i=1}^n (y_i -\bar y)^2 }{2n-2}
\]</span></p>
<p>이제 두 개의 처리를 비교하는 경우, 독립 표본이 아닌 경우를 고려해 보자.</p>
<p>독립 표본이 아닌 대표적인 경우가 대응표본(또는 쌍표본)에 대한 t-검정이다(paired t-test). 대응표본 검정에서는 하나의 개체에 두 개의 처리를 모두 적용하여 각 처리에 대한 반응값을 쌍 <span class="math inline">\((x_i,y_i)\)</span>으로 얻는다.</p>
<p>예를 들어 최초로 허가 받은 약품과 복제약의 생물학적동등성(bioequivalence)을 입증하는 실험에서는 한 사람에게 최초허가약을 투여하여 약의 효과를 보고 일정 시간이 지난 뒤 복제약을 같은 사람에게 투여하여 그 효과를 측정한다. 다른 예로서 두 개의 눈병 치료제를 각각 누에 투여하여 효과를 비교하는 경우도 이러한 대응표본에 속한다. 넓은 의미에서 일란성 쌍둥이에게 각각 다른 처리를 하여 비교하는 것도 대응비교라고 할 수 있다.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>생물학적동등성 실험에서 사용되는 교차실험(crossover design) - 개체 당 2개의 관측치 (각 처리에 대하여 한 개의 관측값)</figcaption>
<p><img src="../myimages/design22.jpg" class="img-fluid figure-img"></p>
</figure>
</div>
<p>가장 단순한 대응비교로서 각 개체애 대하여 두 개의 처리에 대한 대응표본 <span class="math inline">\((x_i,y_i)\)</span>를 관측한다고 가정하자.</p>
<p>이에 대한 분포 모형은 다음과 같다.</p>
<p><span class="math display">\[
d_i = x_i -y_i  \sim_{iid} N(\delta,\sigma^2) \text { where } \delta = \mu_1-\mu_2 = E(x)-E(y)
\]</span></p>
<p>대응비교에서 사용되는 t-통계량은 다음과 같다.</p>
<p><span id="eq-tvalue2"><span class="math display">\[
t = \frac{ \bar d} {s_d / \sqrt{n}} =\frac{ \bar x -\bar y} {s_d / \sqrt{n}}
\tag{7.4}\]</span></span></p>
<p>여기서 <span class="math inline">\(s^2_d\)</span>는 <span class="math inline">\(d_1,d_2,\dots ,d_n\)</span>의 표본분산이다.</p>
<p><span class="math display">\[
s^2_d = \frac{\sum_{i=1}^n (d_i -\bar d)^2}{n-1}
\]</span></p>
<p>위에서 알아본 독립표본에 의한 비교와 대응표본에 의한 비교가 다른 점은 무었일까 생각해 보자.</p>
<p>표본의 비교가 다른 개체에서 추출된 독립인 관측치를 이용하는지 또는 같은 개체에서 추출된 대응하는(독립이 아닌) 관측치를 이용하는지에 따라서 서로 다른 t-통계량을 사용한다. <a href="#eq-tvalue1" class="quarto-xref">식&nbsp;<span>7.3</span></a> 과 <a href="#eq-tvalue2" class="quarto-xref">식&nbsp;<span>7.4</span></a> 에 나타난 t-통계량을 비교하면 분자에 나타난 통계량은 효과의 차이를 나타내는 두 개의 평균의 차이로서 기본적으로 동일하다<span class="math inline">\((\bar d =\bar x -\bar y)\)</span>. 하지만 분모에서는 분자에 나타난 통계량의 표본오차(standard error)를 나타내는 양으로서 서로 다르다.</p>
<p>독립표본에서는 표본의 평균이 서로 독립이므로 다음과 같이 평균의 차이에 대한 분산이 각각의 분산의 합과 같으므로 이에 대한 추정량으로서 합동분산추정량을 이용하였다.</p>
<p><span id="eq-varsum"><span class="math display">\[
Var(\bar x - \bar y) = Var(\bar x) + Var(\bar y)   
\tag{7.5}\]</span></span></p>
<p>대응표본에서는 위의 <a href="#eq-varsum" class="quarto-xref">식&nbsp;<span>7.5</span></a> 을 적용할 수 없다. 왜냐하면 두개의 표본 평균이 서로 독립이 아닐 가능성이 매우 높기 때문이다. 같은 개체에서 나온 관측치는 어떠한 형태로든 서로 관계가 있을 가능성이 높기 때문에 독립을 함부로 가정할 수 없다. 예를 들어 생물학적동등성 실험에서는 약 효과의 차이보다 약이 몸에 흡수되는 개인적인 체질이 관측값에 더 큰 영향을 줄 수 있다.</p>
</section>
<section id="임의효과" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="임의효과"><span class="header-section-number">7.3</span> 임의효과</h2>
<p>확률변수 <span class="math inline">\(x\)</span>와 <span class="math inline">\(y\)</span>가 독립이 아닌 경우 두 모형균의 차이를 비교하기 위하여 비교에 사용된 통계양은 두 확률변수의 차이다.</p>
<p><span class="math display">\[
d_i = x_i - y_i
\]</span></p>
<p>여기서 두 개의 확률변수의 차이를 이용할 때 암시적인 가정은 두 개의 확률변수의 차이를 내면 두 변수에 공통적으로 포함된 개인의 특성이 서로 상쇄되어 처리의 차이만이 확률변수 <span class="math inline">\(d_i\)</span>에 존재한다는 것이다. 지금 설명한 대응비교 모형의 합리적인 가정을 요약하면 다음과 같다.</p>
<ul>
<li>개인의 특성을 반영하는 공통 요인이 두 변수에 모두 영향을 미친다.</li>
<li>따라서 두 관측값 <span class="math inline">\((x_i,y_i)\)</span>가 독립이 아니다</li>
<li>두 관측값의 차이를 내면 공통요인이 서로 상쇄되어 처리효과만 남는다.</li>
</ul>
<p><span class="math display">\[
E(d_i) = \mu_1 - \mu_2
\]</span></p>
<p>위의 가정을 구현할 수 있는 대응비교 모형을 다음과 같은 가법모형(additive models)로 표현할 수 있다.</p>
<p><span id="eq-paired"><span class="math display">\[  
x_i = \mu_1 + a_i + e_{i1}, \quad y_i = \mu_2 + a_i + e_{i2}
\tag{7.6}\]</span></span></p>
<p>여기서 <span class="math inline">\(a_i\)</span>는 두 확률변수 <span class="math inline">\((x_i,y_i)\)</span>에 공통으로 포함된 개인적인 특성을 나타내는 요인이며 위의 <a href="#eq-paired" class="quarto-xref">식&nbsp;<span>7.6</span></a> 는 <a href="#eq-meanmodel" class="quarto-xref">식&nbsp;<span>7.1</span></a> 에 공통요인 <span class="math inline">\(a_i\)</span>가 추가된 형태이다.</p>
<p>두 확률변수 <span class="math inline">\((x_i,y_i)\)</span>가 종속이기 위해서는 다음과 같은 가정을 이용할 수 있다.</p>
<p><span class="math display">\[
a_i \sim N(0, \sigma^2_a), \quad  e_{i1} \sim_{iid}  N(0, \sigma^2_e)  \quad e_{i2} \sim_{iid}  N(0, \sigma^2_e)
\]</span> 여기서 <span class="math inline">\(a_i\)</span>가 평균이 0이고 분산이 <span class="math inline">\(\sigma_a^2\)</span> 인 확률변수이다. 이러한 요인을 <strong>임의효과(random effect)</strong> 라고 하며 모수(parameter)인 평균 <span class="math inline">\(\mu_i\)</span>은 고정효과(fixed effect)라고 부른다. <span class="math inline">\(e_{i1}\)</span>와 <span class="math inline">\(e_{i2}\)</span>들은 모두 독립이며 평균이 <span class="math inline">\(0\)</span> 이고 분산이 <span class="math inline">\(\sigma^2_e\)</span>인 정규분포를 따르는 오차들이다. 또한 <span class="math inline">\(a_i\)</span>와 (<span class="math inline">\(e_{i1}\)</span>,<span class="math inline">\(e_{i2}\)</span>)도 독립이다.</p>
<p>위와 같은 가정에서 두 변수의 차이를 내면 공통요인인 <span class="math inline">\(a_i\)</span>가 제거되어 두 처리의 차이만이 남게되며 <span class="math inline">\(x_i\)</span>와 <span class="math inline">\(y_i\)</span>는 분포의 가정상 독립이 아니다.</p>
<p><span class="math display">\[
\begin{aligned}
d_i &amp;= x_i -y_i \\
   &amp;= \mu_1+ a_i + e_{i1} -(\mu_2+ a_i + e_{i2}) \\
   &amp;= \mu_1 -\mu_2 +(e_{i1}-e_{i2}) \\
   &amp;= \mu_1 -\mu_2 +e^*_i
\end{aligned}
\]</span></p>
<p><span class="math display">\[
\begin{aligned}
Cov(x_i,y_i) &amp;= Cov(\mu_1+ a_i + e_{i1},\mu_2+ a_i + e_{i2}) \\
    &amp; =  Cov(a_i, a_i) \\
    &amp; =  Var(a_i) \\
    &amp; =  \sigma^2_a
\end{aligned}
\]</span></p>
<p>다음 절에서는 여기서 논의한 독립표본과 대응표본의 개념 및 추정법을 일반적인 선형모형으로 확장하여 체계적인 비교를 해볼것이다.</p>
</section>
<section id="repeatmeasure-oneway" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="repeatmeasure-oneway"><span class="header-section-number">7.4</span> 일원배치 모형</h2>
<section id="고정효과-모형" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="고정효과-모형"><span class="header-section-number">7.4.1</span> 고정효과 모형</h3>
<p>먼저 일원배치 요인계획(one-way factor design)이용한 실험을 생각해 보자. 고려하는 요인의 수준의 개수를 <span class="math inline">\(I\)</span>라고 하면 <span class="math inline">\(I\)</span>개의 수준 중에 하나를 임의로 선택하여 실험대상에 적용하는 임의화 방법으로 각 수준마다 <span class="math inline">\(J\)</span>의 관측값을 얻어다고 하자. 다음과 같은 ANOVA모형을 고려하여 분석을 할 수 있다.</p>
<p><span id="eq-ANOVA"><span class="math display">\[
y_{ij} = \mu + \alpha_i + e_{ij}, \quad i=1,2,\dots,I \text{ and } j=1,2,\dots, J  
\tag{7.7}\]</span></span></p>
<p>여기서 <span class="math inline">\(e_{ij}\)</span>는 서로 독립이며 <span class="math inline">\(N(0,\sigma_e^2)\)</span>를 따르는 오차항이다.</p>
<p>ANOVA 모형 <a href="#eq-ANOVA" class="quarto-xref">식&nbsp;<span>7.7</span></a> 에서 <span class="math inline">\(\mu\)</span>와 <span class="math inline">\(\alpha_i\)</span>는 고정효과(fixed effect)라고 부르며 추정해야 할 모수(parameter)이다. 세심하게 설계된 실험에서는 수준에 대한 효과 <span class="math inline">\(\alpha_i\)</span>의 값이 변하지 않게 통제할 수 있는 실험 환경이 가능하다고 생각할 수 있으므로 <span class="math inline">\(\alpha_i\)</span>의 값을 변하지 않는 고정효과로 보는 것이 합리적이다.</p>
<p>일원배치 요인계획을 이용한 실험에서는 주요 관심사가 수준간의 차이가 있는지에 대한 것이며 이는 제곱합을 이용한 ANOVA table에서 F-test를 이용하여 검정할 수 있다.</p>
<p><span class="math display">\[
H_0: \alpha_1 = \alpha_2 =\dots = \alpha_I
\]</span></p>
</section>
<section id="임의효과-모형" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="임의효과-모형"><span class="header-section-number">7.4.2</span> 임의효과 모형</h3>
<p>이제 다음과 같은 자료의 추출을 생각해 보자. 서울시 A구에 초등학교가 20개있다고 하자. 20개의 학교중 6개의 학교를을 임의로 추출하고 추출된 학교에 속한 모든 6학년 학생들에게 과학시험을 보게하여 점수를 얻었다. 이러한 자료에서 학생들의 성적은 모두 같지 않을 것이 당연하며 가장 점수가 낮은 학생부터 높은 학생까지 점수의 변동(variation)이 존재한다. 변동의 요인은 무었일까? 학생의 개인의 차이(예:학생의 지능, 노력 정도, 학습 환경)도 변동의 요인이지만 또한 학교의 차이도 변동의 요인이 될 수 있다.</p>
<p>여기서 학교에 대한 요인은 앞 절에서 본 실험 자료에서 나타나는 고정 효과에 의한 요인과는 성격이 틀리다. 20개의 학교라는 모집단에서 6개의 학교가 추출되었으며 이 때 학교의 차이는 설계된 실험에서는 수준에 대한 효과와는 다르게 표본 추출 때문에 생기는 변동이라고 할 수 있다. 또한 같은 학교에 다니는 학생들은 같은 지역과 교사 등 공통적인 요인에 의하여 영향을 받는다고 가정할 수 있다. 따라서 같은 학교에 다는 학생들의 성적이 독립이 아닐 수도 있다.</p>
<p>이러한 효과를 임의효과(random effect)라고 부르며 학생들의 과학점수에 대한 모형을 다음과 같은 <strong>임의효과모형(random effects model)</strong> 또는 <strong>혼합효과모형(mixed effects model)</strong> 으로 설명할 수 있다.</p>
<p><span id="eq-onewayrandom"><span class="math display">\[
y_{ij} = \mu + a_i + e_{ij}, \quad i=1,2,\dots,I \text{ and } j=1,2,\dots, J  
\tag{7.8}\]</span></span></p>
<p>여기서 <span class="math inline">\(a_i\)</span>는 학교의 효과를 나타내는 임의효과이며 서로 독립이고 <span class="math inline">\(N(0,\sigma_a^2)\)</span>를 따른다. 또한 개인에 대한 효과 또는 오차항 <span class="math inline">\(e_{ij}\)</span>는 서로 독립이며 <span class="math inline">\(N(0,\sigma_e^2)\)</span>를 따른다. 임의효과 <span class="math inline">\(a_i\)</span>와 오차항 <span class="math inline">\(e_{ij}\)</span>는 서로 독립이다. 고정효과 <span class="math inline">\(\mu\)</span>는 전체 평균을 나타내는 모수이다.</p>
<p>학교를 추출할 때 그 효과를 분산이 <span class="math inline">\(\sigma^2_a\)</span>를 가지는 정규모집단에서 추출한다고 가정하는 것이다. 학교를 하나의 군집(cluster)로 생각하고 학교의 효과를 군집효과로 보고 총변동의 일부로서 고려하고 나머지 변동은 오차의 변동으로 개인의 효과 등으로 설명한다.</p>
<p><span class="math display">\[
Var(y_{ij}) =Var(\mu + a_i + e_{ij}) = Var(a_i) + Var(e_{ij}) = \sigma^2_a + \sigma^2_e
\]</span></p>
<p><a href="#eq-onewayrandom" class="quarto-xref">식&nbsp;<span>7.8</span></a> 로 표현된 임의효과를 포함한 혼합모형(일원배치 임의효과 모형; one-way random effect models)의 가장 큰 특징 중에 하나는 같은 군집에 속하는 관측치들은 서로 독립이 아니며 양의 상관관계가 있다.</p>
<p>위의 예제에서 두 학생 <span class="math inline">\(j\)</span>와 <span class="math inline">\(k\)</span>가 같은 학교 <span class="math inline">\(i\)</span>에 속한다면</p>
<p><span class="math display">\[
Cov(y_{ij},y_{ik}) = Cov(  \mu + a_i + e_{ij}, \mu + a_i + e_{ik}) =Cov (a_i, a_i)=\sigma^2_a
\]</span></p>
<p>따라서</p>
<p><span class="math display">\[
corr(y_{ij},y_{ik})= \frac{ Cov(y_{ij},y_{ik})}{\sqrt{Var(y_{ij})Var(y_{ik})} } = \frac{\sigma^2_a }{\sigma^2_a + \sigma^2_e }
\]</span></p>
<p>위의 상관계수를 보면 학교간의 변동의 크기를 나타내는 <span class="math inline">\(\sigma^2_a\)</span> 가 각 개인간의 변동을 나타내는 <span class="math inline">\(\sigma^2_e\)</span>보다 상대적으로 클수록 상관계수가 1에 가까와진다.</p>
<p>보통 <span class="math inline">\(\sigma^2_a\)</span>을 집단간 변동(between-group variance)라 하고 <span class="math inline">\(\sigma^2_e\)</span>를 집단내 변동(within-group variance)라고 한다. 따라서 <span class="math inline">\(\sigma^2_a\)</span>와 <span class="math inline">\(\sigma^2_e\)</span>의 상대적인 크기의 차이에 따라 군집내 관측값의 상관관계가 달라진다.</p>
<p><a href="#eq-onewayrandom" class="quarto-xref">식&nbsp;<span>7.8</span></a> 의 임의효과 모형은 임의효과가 2개 이상인 모형으로 확장될 수 있다. 예제에서 학교를 추출하고 학교내에서 학급을 추출하여 추출된 학급내의 학생들이 시험을 보면 다음과 같은 모형을 적용할 수 있다.</p>
<p><span class="math display">\[
y_{ijk} = \mu + a_i + b_{ij} + e_{ijk}
\]</span> 위의 모형에서 <span class="math inline">\(a_i\)</span>는 <span class="math inline">\(N(0,\sigma^2_a)\)</span>를 따르는 학교에 대한 임의효과, <span class="math inline">\(b_{ij}\)</span>는 <span class="math inline">\(N(0,\sigma^2_b)\)</span>를 따르는 학급에 대한 임의효과, <span class="math inline">\(e_{ijk}\)</span>는 <span class="math inline">\(N(0,\sigma^2_e)\)</span>를 따르는 학생에 대한 임의효과 또는 오차항으로 생각할 수 있다.</p>
<p>임의효과 모형에 고정효과가 같이 포함되어 있는 모형을 혼합모형(mixed model)이라고 부르며 반응변수의 변동에 영향을 미치는 요인들 또는 예측변수 중에서 임의효과와 고정효과를 구별하여 정하고 동시에 모형에 포함시킬수 있다.</p>
<p>예를 들어서 학교를 선택하여 과학시험을 볼 경우에 학기가 시작할 떄 과학교수법 두가지 중 하나를 임의화해서 각 학교에 배정하여 배정된 교수법으로 학생을 가르친 후에 시험을 보았다면 교수법에 대한 효과는 고정효과로 볼 수 있다. 따라서 다음과 같은 모형을 고려할 수 있다.</p>
<p><span id="eq-compmodel"><span class="math display">\[
y_{ij} = \mu + \tau_{k(i)} + a_i + e_{ij}  
\tag{7.9}\]</span></span></p>
<p>여기서 <span class="math inline">\(\tau_{k(i)}\)</span>는 <span class="math inline">\(i\)</span>번째 학교의 교수법에 대한 고정효과이다(교수법이 배정된 결과에 의하여 <span class="math inline">\(k(i)=1\)</span> 또는 <span class="math inline">\(k(i)=2\)</span>이 된다). 이 교수법에 대한 고정효과에 대해서는 두 교수법이 차이가 있는 지에 대한 검정이 주요한 관심사일 것이다 (<span class="math inline">\(H_0: \tau_1=\tau_2\)</span>)</p>
</section>
</section>
<section id="반복측정자료" class="level2 page-columns page-full" data-number="7.5">
<h2 data-number="7.5" class="anchored" data-anchor-id="반복측정자료"><span class="header-section-number">7.5</span> 반복측정자료</h2>
<p>반복측정자료(longitudinal data, repeated measurements)는 관측단위안에서 여러 개의 관측값을 측정한 자료의 형식을 말한다.</p>
<p>예를 들어 환자가 병원을 여러 번 방문하고 방문시마다 혈압을 측정하였다면 한 명의 환자에서 반복 측정한 자료는 서로 독립이 아니다. 또한 가구조사(household survey)에서 가구원의 취업 여부, 건겅 상태등을 여러 해동안 매년 측정하는 경우 이러한 자료를 패널자료(panel data) 또는 longitudinal 자료라고 한다.</p>
<p>이렇게 하나의 관측단위 안에서 측정한 자료들은 서로 독립이 아닌 특징이 있고 자료를 분석하는 경우 이러한 자료들의 종속구조를 고려하는 모형을 사용하는 것이 적절하다. 이렇게 반복측정자료에서 반복자료들의 공분산구조를 설정하는 통계적 방법들은 다양하지만 대표적으로 쉽게 사용할 수 있는 방법이 임의효과를 포함한 혼합모형을 사용하는 방법이다.</p>
<p><code>lme4</code> 패키지에 자료인 <code>spleepstudy</code>는 화물트럭 운전사들에 대한 수면부족 현상에 대하여 연구한 자료이다. 18명의 운전자들이 매일 3시간의 수면(부족한 수면)을 하면서 매일 일정한 동작의 반응시간을 10일동안 반복적으로 측정한 자료가 있다.</p>
<p>한명의 운전사에게 10일 동안의 반응에 대한 측정자료 10개가 존재하므로 이는 반복측정 자료이며 이러한 10개의 자료는 독립이 아니다.</p>
<p>일단 자료의 구조를 살펴보자. 반응변수 <code>Reaction</code>은 반응시간(ms)를 나타내며 설명변수로서 <code>Days</code>는 날짜(<span class="math inline">\(t=0,1,2,\dots,9\)</span>), <code>Subject</code> 는 운전자의 고유번호를 나타낸다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(sleepstudy)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   180 obs. of  3 variables:
 $ Reaction: num  250 259 251 321 357 ...
 $ Days    : num  0 1 2 3 4 5 6 7 8 9 ...
 $ Subject : Factor w/ 18 levels "308","309","310",..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sleepstudy,<span class="at">n=</span><span class="dv">20</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Reaction Days Subject
1  249.5600    0     308
2  258.7047    1     308
3  250.8006    2     308
4  321.4398    3     308
5  356.8519    4     308
6  414.6901    5     308
7  382.2038    6     308
8  290.1486    7     308
9  430.5853    8     308
10 466.3535    9     308
11 222.7339    0     309
12 205.2658    1     309
13 202.9778    2     309
14 204.7070    3     309
15 207.7161    4     309
16 215.9618    5     309
17 213.6303    6     309
18 217.7272    7     309
19 224.2957    8     309
20 237.3142    9     309</code></pre>
</div>
</div>
<p>각 운전자에 대한 10일 간의 반응속도가 시간에 따라 어떻게 변하는 가를 알아보자. 전반적으로 시간이 지나면서 운전자들의 반응시간이 증가하고 있음을 알 수 있다. 또한 개인 별로 반응 시간의 변화와 패턴이 다르다는 것을 알 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleepstudy, <span class="fu">aes</span>(<span class="at">x=</span>Days, <span class="at">y=</span>Reaction)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>     <span class="fu">geom_point</span>(<span class="at">size=</span><span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">facet_wrap</span>(<span class="st">"Subject"</span>, <span class="at">labeller =</span> label_both)<span class="sc">+</span> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">theme_bw</span>()</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="random_effect_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<section id="선형-회귀모형" class="level3" data-number="7.5.1">
<h3 data-number="7.5.1" class="anchored" data-anchor-id="선형-회귀모형"><span class="header-section-number">7.5.1</span> 선형 회귀모형</h3>
<p>각 운전자 <span class="math inline">\(i\)</span> 에 대하여 10일간 측정한 반응속도 <span class="math inline">\(y_{ij}\)</span>를 시간에 대하여 선형모형으로 적합하면 <strong>개체별 선형회귀 모형(individual model)</strong> 을 다음과 같이 표시할 수 있다.</p>
<p><span id="eq-lmlist1"><span class="math display">\[
y_{ij} = \beta_{0i} + \beta_{1i} t_j + e_{ij},\quad i=1,2,\dots,18,\quad j=1,2,\dots,10
\tag{7.10}\]</span></span></p>
<p>여기서 오차항 <span class="math inline">\(e_{ij}\)</span>은 서로 독립이며 <span class="math inline">\(N(0, \sigma^2_e)\)</span>를 따른다고 가정한다.</p>
<p>행렬식으로는 다음과 같이 나타낼 수 있다.</p>
<p><span class="math display">\[  
\pmb y_i =\pmb X_i \pmb \beta_{i} +\pmb e_i ,\quad i=1,2,\dots,18
\]</span></p>
<p>여기서 <span class="math display">\[
\pmb y_i=\begin{bmatrix}
y_{i1} \\
y_{i2} \\
\vdots \\
y_{i,10}
\end{bmatrix},~ \pmb X_i =
\begin{bmatrix}
1 &amp; 0 \\
1 &amp; 1 \\
\vdots &amp; \vdots  \\
1 &amp; 9
\end{bmatrix}, \pmb \beta_i=
\begin{bmatrix}
\beta_{0i} \\
\beta_{1i} \\
\end{bmatrix}, \pmb e_i=
\begin{bmatrix}
e_{i1} \\
e_{i2} \\
\vdots \\
e_{i,10}
\end{bmatrix}
\]</span></p>
<p>위의 식에서 <span class="math inline">\(\beta_{0i}\)</span>와 <span class="math inline">\(\beta_{1i}\)</span>는 <span class="math inline">\(i\)</span>번째 운전사의 반응속도를 설명하는 회귀직선의 절편과 기울기이다.</p>
<p>절편 <span class="math inline">\(\beta_{0i}\)</span>는 실험 시작때 반응속도를 의미하고 기울기 <span class="math inline">\(\beta_{1i}\)</span>는 실험이 진행되는 동안 반응속도가 어떻게 변하는 지 변화의 방향과 크기를 보여준다. 함수 <code>lmList</code>를 아래와 같이 이용하면 식 <a href="#eq-lmlist1" class="quarto-xref">식&nbsp;<span>7.10</span></a> 을 각 운전사마다 적합시켜 각각의 절편과 기울기를 구할 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>lmf1 <span class="ot">&lt;-</span> <span class="fu">lmList</span>(Reaction <span class="sc">~</span> Days <span class="sc">|</span> Subject, sleepstudy)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>lmf1</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call: lmList(formula = Reaction ~ Days | Subject, data = sleepstudy) 
Coefficients:
    (Intercept)      Days
308    244.1927 21.764702
309    205.0549  2.261785
310    203.4842  6.114899
330    289.6851  3.008073
331    285.7390  5.266019
332    264.2516  9.566768
333    275.0191  9.142045
334    240.1629 12.253141
335    263.0347 -2.881034
337    290.1041 19.025974
349    215.1118 13.493933
350    225.8346 19.504017
351    261.1470  6.433498
352    276.3721 13.566549
369    254.9681 11.348109
370    210.4491 18.056151
371    253.6360  9.188445
372    267.0448 11.298073

Degrees of freedom: 180 total; 144 residual
Residual standard error: 25.59182</code></pre>
</div>
</div>
<p>위에서 고려한 개체별 선형회귀 직선들을 그림으로 그려보면 다음과 같이 나타난다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleepstudy, <span class="fu">aes</span>(<span class="at">x=</span>Days, <span class="at">y=</span>Reaction)) <span class="sc">+</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>,<span class="at">se=</span>F,<span class="at">linewidth=</span><span class="fl">0.5</span>)<span class="sc">+</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="st">"Subject"</span>, <span class="at">labeller =</span> label_both)<span class="sc">+</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="random_effect_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>18개의 절편과 기울기는 큰 상관관계는 없는것으로 보이지만 약한 음의 상관계수가 나타났다. 절편과 기울기에 대한 분포를 보기 위하여 상자그림을 그려보면 평균을 중심으로 대칭인 분포를 보이고 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="fu">coef</span>(lmf1))</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            (Intercept)       Days
(Intercept)   1.0000000 -0.1375534
Days         -0.1375534  1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">coef</span>(lmf1),<span class="at">main=</span><span class="st">"intercepts and slopes on drivers: sleep study "</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="random_effect_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">coef</span>(lmf1)[<span class="dv">1</span>])</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">coef</span>(lmf1)[<span class="dv">2</span>])</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="fig-coef-repeat" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="figure quarto-float-caption quarto-float-fig" id="fig-coef-repeat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
그림&nbsp;7.1: 개별 선형회귀모형에서 절볓과 기울기의 분포
</figcaption>
<div aria-describedby="fig-coef-repeat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-coef-repeat" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-coef-repeat-1" class="quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<figcaption class="figure quarto-subfloat-caption quarto-subfloat-fig" id="fig-coef-repeat-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) 절편
</figcaption>
<div aria-describedby="fig-coef-repeat-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="random_effect_files/figure-html/fig-coef-repeat-1.png" class="img-fluid figure-img" data-ref-parent="fig-coef-repeat" width="672">
</div>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-coef-repeat" style="flex-basis: 50.0%;justify-content: center;">
<div id="fig-coef-repeat-2" class="quarto-figure quarto-figure-center anchored" width="672">
<figure class="quarto-float quarto-subfloat-fig figure">
<figcaption class="figure quarto-subfloat-caption quarto-subfloat-fig" id="fig-coef-repeat-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) 기울기
</figcaption>
<div aria-describedby="fig-coef-repeat-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="random_effect_files/figure-html/fig-coef-repeat-2.png" class="img-fluid figure-img" data-ref-parent="fig-coef-repeat" width="672">
</div>
</figure>
</div>
</div>
</div>
</div>
</figure>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">coef</span>(lmf1)[<span class="dv">1</span>])</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="random_effect_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>이제 각 운전사에 대하여 회귀식을 따로 적합하지 않고 전체 운전사들의 자료를 모두 합쳐서 하나의 회귀식을 고려할 수 있다. 개체의 특성을 반영하는 모형이 아닌 전체 모집단에 대한 <strong>모집단 평균 모형(population mean model)</strong> 을 고려하는 것이다.</p>
<p><span id="eq-popmodel"><span class="math display">\[
y_{ij} = \beta_0 + \beta_1 t_j + e_{ij} ,\quad i=1,2\dots,18,  j=1,2, \dots, 10
\tag{7.11}\]</span></span></p>
<p>여기서 오차항은 서로 독립이며 <span class="math inline">\(N(0, \sigma^2_e)\)</span>를 따른다고 가정한다.</p>
<p>위와 같은 전체 운전사 집단의 관측값을 운전자의 특성을 고려하지 않고 세운 모형으로서 시간에 따른 반응시간에 대한 모집단의 전체적인 평균적 함수 관계를 파악하는 모형이라고 할 수 있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>lmpop <span class="ot">&lt;-</span> <span class="fu">lm</span>(Reaction <span class="sc">~</span> Days, sleepstudy)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lmpop)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Reaction ~ Days, data = sleepstudy)

Residuals:
     Min       1Q   Median       3Q      Max 
-110.848  -27.483    1.546   26.142  139.953 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  251.405      6.610  38.033  &lt; 2e-16 ***
Days          10.467      1.238   8.454 9.89e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 47.71 on 178 degrees of freedom
Multiple R-squared:  0.2865,    Adjusted R-squared:  0.2825 
F-statistic: 71.46 on 1 and 178 DF,  p-value: 9.894e-15</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(sleepstudy, <span class="fu">plot</span>(Days, Reaction,<span class="at">main=</span><span class="st">"Population and individual regression lines"</span>))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span><span class="fu">coef</span>(lmpop)[<span class="dv">1</span>], <span class="at">b=</span><span class="fu">coef</span>(lmpop)[<span class="dv">2</span>],<span class="at">lwd=</span><span class="dv">3</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">18</span> ) {</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  xx <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">coef</span>(lmf1)[i,])</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span>xx[<span class="dv">1</span>],<span class="at">b=</span>xx[<span class="dv">2</span>], <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="random_effect_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><a href="#eq-lmlist1" class="quarto-xref">식&nbsp;<span>7.10</span></a> 의 개체별 선형회귀 모형에서 얻은 모든 절편들과 기울기들의 평균을 구하면 다음과 같다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(<span class="fu">coef</span>(lmf1),<span class="dv">2</span>,mean)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        Days 
  251.40510    10.46729 </code></pre>
</div>
</div>
<p>다음으로 <a href="#eq-popmodel" class="quarto-xref">식&nbsp;<span>7.11</span></a> 의 선형회귀 모형에서 얻은 절편과 기울기의 평균을 구하면 다음과 같다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lmpop)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        Days 
  251.40510    10.46729 </code></pre>
</div>
</div>
<p>각 운전사에 대하여 <a href="#eq-lmlist1" class="quarto-xref">식&nbsp;<span>7.10</span></a> 의 개체별로 적합한 회귀식에서 구한 계수들<span class="math inline">\((\hat \beta_{0i}, \hat \beta_{1i})\)</span> 와 <a href="#eq-popmodel" class="quarto-xref">식&nbsp;<span>7.11</span></a> 의 모집단 평균 회귀모형에서 구한서 계수 <span class="math inline">\((\hat \beta_{0}, \hat \beta_{1})\)</span>의 관계를 보면 개체별로 적합한 회귀 계수들의 평균이 모집단 평균 회귀모형의 계수와 매우 가까운 사실을 알 수 있다.</p>
</section>
<section id="임의계수-모형" class="level3" data-number="7.5.2">
<h3 data-number="7.5.2" class="anchored" data-anchor-id="임의계수-모형"><span class="header-section-number">7.5.2</span> 임의계수 모형</h3>
<p>앞 절의 모형과 분석에서 알 수 있듯이 한 개체에 대하여 여러 개의 관측값을 측정한 자료에 회귀방정식을 각각 적합시켜보고 또한 개체의 특성을 고려하지않은 전체 모형을 적합해보면 다음과 같은 두 가지 결과를 볼 수 있다.</p>
<ul>
<li>각 개체별 회귀식은 개인의 특성을 반영한다. 즉, 개체에 따라 시간에 따른 반응시간의 변화가 다르게 나타난다.</li>
<li>하지만 개인별로 볼 때도 전체적으로는 시간에 따라서 반응시간이 증가하는 경향이 있음을 알 수 있다.</li>
<li>전체 자료에 적합한 모형을 보면 개인별로 적합한 모형의 공통적인 성격, 즉 시간에 따른 반응시간의 증가를 알 수 있다.</li>
<li>이러한 결과를 보고 각 개인의 변화는 전체적인 변화를 따르면서 각 개인의 특성이 반영되었다고 가정할 수 있다.</li>
</ul>
<p>위에서 논의하였듯이 전체적인 경향과 개인의 특성을 동시에 고려할 수 있는 모형이 생각할 수 있고 이러한 모형이 다음과 같은 모형이다.</p>
<p><span id="eq-repeat"><span class="math display">\[
y_{ij} = (\beta_0 + b_{0i}) + (\beta_1 + b_{1i}) t_j + e_{ij}
\tag{7.12}\]</span></span></p>
<p><a href="#eq-repeat" class="quarto-xref">식&nbsp;<span>7.12</span></a> 는 절편과 기울기가 두 개의 구성 요소로 더해져서 표현된다. 기울기는 <span class="math inline">\(\beta_1+b_{1i}\)</span>로서 나타내어지며 <span class="math inline">\(\beta_1\)</span>은 모집단이 가지는 공통적인 경향을 반영하는 모수이고 <span class="math inline">\(b_{1i}\)</span>는 <span class="math inline">\(i\)</span> 번째 개체의 특성을 반영한 확률변수이다. 절편도 유사한 형식으로 구성된다.</p>
<p>각 개인에 대한 특성을 나타내는 변수 <span class="math inline">\((b_{0i}, b_{1i})\)</span> 을 확률변수로 설정하고 이를 모수(<span class="math inline">\(\beta_0, \beta_1)\)</span> (parameter or fixed effect)와 구별하여 임의효과(random effect)라고 한다. 임의효과는 모집단을 구성하는 개인이 표본에 추출되었다고 생각하며 확률분포를 따른다고 가정한다. 반복측정자료에서 인의효과를 공통으로 가지고 있는 관측치는 독립이 아니게 돼며 따라서 같은 개체에서 나온 관측값은 독립이 아니다.</p>
<p>18명에 대한 회귀직선의 절편과 기울기를 보면 개인의 차이에 따른 변동을 볼 수 있으며 이러한 각 개인간의 변동을 임의효과를 이용하여 다음과 같은 모형을 생각해보자.</p>
<p><span class="math display">\[
\pmb \beta_i=
\begin{bmatrix}
\beta_{0} \\
\beta_{1} \\
\end{bmatrix}
+\begin{bmatrix}
b_{0i} \\
b_{1i} \\
\end{bmatrix}
=
\pmb \beta + {\pmb b}_i
\]</span></p>
<p><span class="math display">\[
{\pmb b}_i =
\begin{bmatrix}
b_{0i} \\
b_{1i} \\
\end{bmatrix} \sim
N \left (
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix}
,
\begin{bmatrix}
\sigma^2_{b1} &amp; \rho \sigma_{b1} \sigma_{b2}\\
\rho \sigma_{b1} \sigma_{b2} &amp; \sigma^2_{b2} \\
\end{bmatrix}
\right )
\]</span></p>
<p>위의 모형은 각 개인의 회귀직선에서 각 절편과 기울기가 전체평균 <span class="math inline">\(\beta_0\)</span>와 <span class="math inline">\(\beta_1\)</span>를 따르며 각 개인의 차이는 전체평균에 임의효과인 <span class="math inline">\(b_{0i}\)</span>와 <span class="math inline">\(b_{1i}\)</span>가 더해져서 나타난다는 것을 의미한다.</p>
<p>이변량 임의효과 <span class="math inline">\(b_{0i}\)</span>와 <span class="math inline">\(b_{1i}\)</span>는 이변량 정규분포를 따르며 각각의 분산과 상관계수가 <span class="math inline">\(\sigma^2_{b1}\)</span>, <span class="math inline">\(\sigma^2_{b2}\)</span>, <span class="math inline">\(\rho\)</span>이다.</p>
<p>다른 개체에 대한 임의효과는 서로 독립이며 임의 효과와 오차항은 독립이다. 여기서 오차항은 서로 독립이며 <span class="math inline">\(N(0, \sigma^2_e)\)</span>를 따른다고 가정한다.</p>
<p><span class="math display">\[  Cov(\pmb b_{i}, \pmb b_{j}) =\pmb 0 \text{ when } i \ne j,\quad
Cov(\pmb b_{i}, e_{jk}) =\pmb 0 \text{ for all } i,j,k \]</span></p>
</section>
<section id="혼합효과-모형" class="level3" data-number="7.5.3">
<h3 data-number="7.5.3" class="anchored" data-anchor-id="혼합효과-모형"><span class="header-section-number">7.5.3</span> 혼합효과 모형</h3>
<p>임의계수모형을 각 개인 <span class="math inline">\(i\)</span>에 대하여 행렬식으로 표시하면 다음과 같은 혼합효과모형(mixed effects model)으로 나타낼 수 있다. 혼합효과모형은 반응변수에 영향을 미치는 효과를 고정효과와 임의효과로 나누어 설명하는 모형이다.</p>
<p><span class="math display">\[  
\pmb y_i = \pmb X_i \pmb \beta + \pmb Z_i \pmb b_i + \pmb e_i
\]</span></p>
<p>여기서</p>
<p><span class="math display">\[  
\pmb y_i=\begin{bmatrix}
y_{i1} \\
y_{i2} \\
\vdots \\
y_{i,10}
\end{bmatrix},~\pmb X_i =
\begin{bmatrix}
1 &amp; 0 \\
1 &amp; 1 \\
\vdots &amp; \vdots  \\
1 &amp; 9
\end{bmatrix}, \pmb  \beta=
\begin{bmatrix}
\beta_{0} \\
\beta_{1} \\
\end{bmatrix}, ~\pmb Z_i =
\begin{bmatrix}
1 &amp; 0 \\
1 &amp; 1 \\
\vdots &amp; \vdots  \\
1 &amp; 9
\end{bmatrix},~ \pmb b_i =
\begin{bmatrix}
b_{0i} \\
b_{1i} \\
\end{bmatrix},~
\pmb  e_i=
\begin{bmatrix}
e_{i1} \\
e_{i2} \\
\vdots \\
e_{i,10}
\end{bmatrix}
\]</span></p>
<p>위의 각 개인에 대한 모형을 모두 합쳐서 하나의 혼합효과모형으로 나타내면 다음과 같이 표현할 수 있다.</p>
<p><span id="eq-lme1"><span class="math display">\[
\pmb  y = \pmb  X \pmb \beta + \pmb Z \pmb b + \pmb e
\tag{7.13}\]</span></span> \end{equation}</p>
<p>여기서 반응변수 벡터 <span class="math inline">\(\pmb y\)</span>와 고정효과 <span class="math inline">\(\pmb \beta\)</span>에 대한 계획행렬 <span class="math inline">\(X\)</span>는 각 개인의 반응변수 벡터 <span class="math inline">\(\pmb y_i\)</span>와 <span class="math inline">\(\pmb X_i\)</span>를 행으로 쌓아놓은 것으로 표현된다. 오차항에 대한 벡터 <span class="math inline">\(\pmb e\)</span>도 동일한 형식의 벡터이다.</p>
<p><span class="math display">\[  
\pmb y_i=\begin{bmatrix}
\pmb y_{1} \\
\pmb y_{2} \\
\vdots \\
\pmb y_{18}
\end{bmatrix},~\pmb X =
\begin{bmatrix}
\pmb X_1 \\
\pmb X_2 \\
\vdots \\
\pmb  X_{18}
\end{bmatrix}
~ \pmb e =
\begin{bmatrix}
\pmb e_1 \\
\pmb e_2 \\
\vdots  \\
\pmb e_{18}
\end{bmatrix}
\]</span></p>
<p>임의효과 벡터 <span class="math inline">\({\pmb b}\)</span> 는 각 개인에 대한 임의효과벡터 <span class="math inline">\(\pmb b_i\)</span>를 행으로 쌓아놓은것과 같고 임의효과에 대한 계획행렬 <span class="math inline">\(\pmb Z\)</span>는 각 개인의 계획행렬 <span class="math inline">\(\pmb Z_i\)</span>를 대각원소로 같은 행렬이다.</p>
<p><span class="math display">\[
\pmb b=\begin{bmatrix}
\pmb b_{1} \\
\pmb b_{2} \\
\vdots \\
\pmb b_{18}
\end{bmatrix},~\pmb Z =
\begin{bmatrix}
\pmb Z_1 &amp; 0 &amp; \dots &amp; 0 \\
0   &amp; \pmb Z_2 &amp; \dots &amp; 0 \\
\vdots &amp; \vdots &amp; \vdots &amp; \vdots  \\
0 &amp; 0 &amp; \dots &amp; \pmb Z_{18}
\end{bmatrix}
\]</span></p>
<p>임의효과는 개인의 특성을 설명하는 효과로서 모집단을 구성하는 개인이 표본에 추출되었다고 생각하며 확률분포를 따른다고 가정한다. 반복측정자료에서 임의효과를 공통으로 가지고 있는 관측치는 독립이 아니게 돼며 따라서 같은 개체에서 나온 관측값은 독립이 아니다.</p>
</section>
<section id="선형혼합모형의-적합" class="level3" data-number="7.5.4">
<h3 data-number="7.5.4" class="anchored" data-anchor-id="선형혼합모형의-적합"><span class="header-section-number">7.5.4</span> 선형혼합모형의 적합</h3>
<p>혼합모형 <a href="#eq-lme1" class="quarto-xref">식&nbsp;<span>7.13</span></a> 은 <code>lmer()</code> 함수를 이용하여 적합시켜보자. 모형식에서 <code>(1 + Days|Subject)</code> 는 각 개체 <code>Subject</code> 에 대하여 절편 <code>1</code> 과 기울기 <code>Days</code>에 임의효과를 포함한다고 지정한다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>fm1 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Reaction <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Days <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> Days<span class="sc">|</span>Subject), sleepstudy)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: Reaction ~ 1 + Days + (1 + Days | Subject)
   Data: sleepstudy

REML criterion at convergence: 1743.6

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.9536 -0.4634  0.0231  0.4634  5.1793 

Random effects:
 Groups   Name        Variance Std.Dev. Corr
 Subject  (Intercept) 612.10   24.741       
          Days         35.07    5.922   0.07
 Residual             654.94   25.592       
Number of obs: 180, groups:  Subject, 18

Fixed effects:
            Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)  251.405      6.825  17.000  36.838  &lt; 2e-16 ***
Days          10.467      1.546  17.000   6.771 3.26e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
     (Intr)
Days -0.138</code></pre>
</div>
</div>
<p>위의 혼합모형 적합결과를 살펴보자. 첫째로 고정효과에 대한 추정식은 다음과 같다</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fixef</span>(fm1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)        Days 
  251.40510    10.46729 </code></pre>
</div>
</div>
<p><span class="math display">\[
\begin{bmatrix}
\hat {\beta}_{0} \\
\hat {\beta}_{1} \\
\end{bmatrix}
=
\begin{bmatrix}
251.4051048 \\
10.467286
\end{bmatrix}
\]</span></p>
<p>또한 오차항에 대한 분산 및 임의효과의 분산성분과 상관계수는 다음과 같이 나타난다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">VarCorr</span>(fm1)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Groups   Name        Std.Dev. Corr 
 Subject  (Intercept) 24.7407       
          Days         5.9221  0.066
 Residual             25.5918       </code></pre>
</div>
</div>
<p><span class="math display">\[
\begin{aligned}
\hat \sigma_{b1} &amp; =  24.740658 \\
\hat \sigma_{b2} &amp; =  5.9221377 \\
\hat \rho &amp; = 0.0655512 \\
\hat \sigma_e &amp; = 25.5917957
\end{aligned}
\]</span></p>
</section>
<section id="임의효과에-대한-예측" class="level3" data-number="7.5.5">
<h3 data-number="7.5.5" class="anchored" data-anchor-id="임의효과에-대한-예측"><span class="header-section-number">7.5.5</span> 임의효과에 대한 예측</h3>
<p>이제 임의효과 <span class="math inline">\(\pmb b_i =(b_{0i}, b_{1i})^t\)</span>에 대한 예측(prediction)을 생각해보자. 우리는 오직 관측벡터 <span class="math inline">\(\pmb y_i\)</span>만을 관측하고 임의효과 <span class="math inline">\(\pmb b_i\)</span>는 관측을 할 수 없는 확률변수이다. 하지만 주어진 관측벡터와 추정된 분산으로 임의효과의 값을 예측할 수있으며 그 결과는 다음과 같다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>re <span class="ot">&lt;-</span> <span class="fu">ranef</span>(fm1)<span class="sc">$</span>Subject</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>re</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    (Intercept)        Days
308   2.2585509   9.1989758
309 -40.3987381  -8.6196806
310 -38.9604090  -5.4488565
330  23.6906196  -4.8143503
331  22.2603126  -3.0699116
332   9.0395679  -0.2721770
333  16.8405086  -0.2236361
334  -7.2326151   1.0745816
335  -0.3336684 -10.7521652
337  34.8904868   8.6282652
349 -25.2102286   1.1734322
350 -13.0700342   6.6142178
351   4.5778642  -3.0152621
352  20.8636782   3.5360011
369   3.2754656   0.8722149
370 -25.6129993   4.8224850
371   0.8070461  -0.9881562
372  12.3145921   1.2840221</code></pre>
</div>
</div>
<p>예를 들어 첫 번째 운전자에 대한 절편과 기울기의 임의효과에 대한 예측값은 다음과 같다.</p>
<p><span class="math display">\[ {\hat b}_{0i} = 2.2585509, \quad  {\hat b}_{1i} =   9.1989758 \]</span> 위에서 구한 절편과 기울기에 대한 임의효과들의 산포도를 보면 다음과 같다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(re, <span class="at">main =</span><span class="st">"prediction of random effects "</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="random_effect_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>예측된 각 개인의 절편과 기울기에 대한 임의효과의 예측값 <span class="math inline">\({\hat b}_{0i}\)</span>과 <span class="math inline">\({\hat b}_{1i}\)</span>에 고정효과의 추정량 <span class="math inline">\(\hat \beta_0\)</span>와 <span class="math inline">\(\hat \beta_1\)</span>에 각각 더해주면 각 개인의 절편과 기울기에 대한 예측값을 구할 수 있다.</p>
<p><span class="math display">\[
{\hat \beta}_{0i} = \hat \beta_0 + {\hat b}_{0i} , \quad
{\hat \beta}_{1i} = \hat \beta_1 + {\hat b}_{1i}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">as.numeric</span>(<span class="fu">fixef</span>(fm1)),<span class="dv">18</span>,<span class="dv">2</span>,<span class="at">byrow=</span>T)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>beta <span class="sc">+</span> re </span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    (Intercept)       Days
308    253.6637 19.6662617
309    211.0064  1.8476053
310    212.4447  5.0184295
330    275.0957  5.6529356
331    273.6654  7.3973743
332    260.4447 10.1951090
333    268.2456 10.2436499
334    244.1725 11.5418676
335    251.0714 -0.2848792
337    286.2956 19.0955511
349    226.1949 11.6407181
350    238.3351 17.0815038
351    255.9830  7.4520239
352    272.2688 14.0032871
369    254.6806 11.3395008
370    225.7921 15.2897709
371    252.2122  9.4791297
372    263.7197 11.7513080</code></pre>
</div>
</div>
<p>예를 들어 선형혼합모형에서 첫 번째 운전자에 대한 절편과 기울기에 대한 추정값은 다음과 같다.</p>
<p><span class="math display">\[
{\hat \beta}_{0i} =  253.6637,  \quad {\hat \beta}_{1i} = 19.6662617
\]</span></p>
</section>
<section id="수축-현상" class="level3 page-columns page-full" data-number="7.5.6">
<h3 data-number="7.5.6" class="anchored" data-anchor-id="수축-현상"><span class="header-section-number">7.5.6</span> 수축 현상</h3>
<p>각 운전자에 대해 개체별 회귀직선 <a href="#eq-lmlist1" class="quarto-xref">식&nbsp;<span>7.10</span></a> 과 임의계수 모형 <a href="#eq-lmlist1" class="quarto-xref">식&nbsp;<span>7.10</span></a> 적합시켜서 얻은 18개의 절편과 기울기를 비교해보자.</p>
<p>먼저 개체별 회귀직선에서 적합한 절편과 기울기는 다음과 같다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>ab_lines_ind <span class="ot">&lt;-</span> <span class="fu">coef</span>(lmf1) <span class="sc">%&gt;%</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">rownames_to_column</span>(<span class="st">"Subject"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">intercept =</span> <span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">add_column</span>(<span class="at">Model =</span> <span class="st">"개체별 모형"</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>ab_lines_ind</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Subject intercept      Days       Model
1      308  244.1927 21.764702 개체별 모형
2      309  205.0549  2.261785 개체별 모형
3      310  203.4842  6.114899 개체별 모형
4      330  289.6851  3.008073 개체별 모형
5      331  285.7390  5.266019 개체별 모형
6      332  264.2516  9.566768 개체별 모형
7      333  275.0191  9.142045 개체별 모형
8      334  240.1629 12.253141 개체별 모형
9      335  263.0347 -2.881034 개체별 모형
10     337  290.1041 19.025974 개체별 모형
11     349  215.1118 13.493933 개체별 모형
12     350  225.8346 19.504017 개체별 모형
13     351  261.1470  6.433498 개체별 모형
14     352  276.3721 13.566549 개체별 모형
15     369  254.9681 11.348109 개체별 모형
16     370  210.4491 18.056151 개체별 모형
17     371  253.6360  9.188445 개체별 모형
18     372  267.0448 11.298073 개체별 모형</code></pre>
</div>
</div>
<p>이제 <a href="#eq-repeat" class="quarto-xref">식&nbsp;<span>7.12</span></a> 의 임의계수 모형에서 적합한 기울기와 절편은 다음과 같다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>ab_lines_random <span class="ot">&lt;-</span> <span class="fu">coef</span>(fm1)[[<span class="st">"Subject"</span>]] <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">rownames_to_column</span>(<span class="st">"Subject"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">intercept =</span> <span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  tibble<span class="sc">::</span><span class="fu">add_column</span>(<span class="at">Model =</span> <span class="st">"임의계수 모형"</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>ab_lines_random </span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Subject intercept       Days         Model
1      308  253.6637 19.6662617 임의계수 모형
2      309  211.0064  1.8476053 임의계수 모형
3      310  212.4447  5.0184295 임의계수 모형
4      330  275.0957  5.6529356 임의계수 모형
5      331  273.6654  7.3973743 임의계수 모형
6      332  260.4447 10.1951090 임의계수 모형
7      333  268.2456 10.2436499 임의계수 모형
8      334  244.1725 11.5418676 임의계수 모형
9      335  251.0714 -0.2848792 임의계수 모형
10     337  286.2956 19.0955511 임의계수 모형
11     349  226.1949 11.6407181 임의계수 모형
12     350  238.3351 17.0815038 임의계수 모형
13     351  255.9830  7.4520239 임의계수 모형
14     352  272.2688 14.0032871 임의계수 모형
15     369  254.6806 11.3395008 임의계수 모형
16     370  225.7921 15.2897709 임의계수 모형
17     371  252.2122  9.4791297 임의계수 모형
18     372  263.7197 11.7513080 임의계수 모형</code></pre>
</div>
</div>
<p>이제 개체별 회귀직선 <a href="#eq-lmlist1" class="quarto-xref">식&nbsp;<span>7.10</span></a> 과 임의계수 모형 <a href="#eq-lmlist1" class="quarto-xref">식&nbsp;<span>7.10</span></a> 적합시켜서 얻은 18명의 개체에 대한 선형회귀 모형을 그림으로 그려보자.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>ab_lines_pop <span class="ot">&lt;-</span> <span class="fu">data_frame</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Subject =</span> <span class="fu">unique</span>(sleepstudy<span class="sc">$</span>Subject),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">intercept =</span> <span class="fu">coef</span>(<span class="fu">lm</span>(Reaction <span class="sc">~</span> Days, sleepstudy))[<span class="dv">1</span>],</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Days =</span> <span class="fu">coef</span>(<span class="fu">lm</span>(Reaction <span class="sc">~</span> Days, sleepstudy))[<span class="dv">2</span>],</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="st">"모집단 평균모형"</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `data_frame()` was deprecated in tibble 1.1.0.
ℹ Please use `tibble()` instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>all_lines <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(ab_lines_pop, ab_lines_ind, ab_lines_random)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(all_lines,<span class="dv">5</span>) </span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  Subject intercept  Days Model          
  &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;          
1 308          251.  10.5 모집단 평균모형
2 309          251.  10.5 모집단 평균모형
3 310          251.  10.5 모집단 평균모형
4 330          251.  10.5 모집단 평균모형
5 331          251.  10.5 모집단 평균모형</code></pre>
</div>
</div>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sleepstudy, <span class="fu">aes</span>(<span class="at">x=</span>Days, <span class="at">y=</span>Reaction)) <span class="sc">+</span> </span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="fl">0.7</span>) <span class="sc">+</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="fu">aes</span>(<span class="at">intercept =</span> intercept, <span class="at">slope =</span> Days, <span class="at">color=</span>Model), <span class="at">data =</span> all_lines) <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="st">"Subject"</span>) <span class="sc">+</span> </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>) </span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display page-columns page-full">
<div class="page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="random_effect_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img column-screen-inset-right" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>이렇게 혼합모형을 통해서 얻은 각 개인의 절편과 기울기에 대한 예측값과 각각의 개체별 선형회귀 직선을 따로 적합하여 얻은 절편과 기울기의 관계를 그림으로 그려보면 다음과 같다.</p>
<p>혼합모형을 통해서 얻은 각 개인의 절편과 기울기는 절편과 기울기의 전체평균값 방향으로 수축되는 경향(shrinkage)을 볼수있다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">bind_rows</span>(ab_lines_ind, ab_lines_random)) <span class="sc">+</span> </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> intercept, <span class="at">y =</span> Days, <span class="at">color =</span> Model) <span class="sc">+</span> </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> ab_lines_pop) <span class="sc">+</span> </span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>(<span class="fu">aes</span>(<span class="at">group =</span> Subject), </span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">arrow =</span> <span class="fu">arrow</span>(<span class="at">length =</span> <span class="fu">unit</span>(.<span class="dv">02</span>, <span class="st">"npc"</span>))) <span class="sc">+</span> </span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> </span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>) <span class="sc">+</span> </span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"회귀계수의 수축"</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="random_effect_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="모형의-비교" class="level3" data-number="7.5.7">
<h3 data-number="7.5.7" class="anchored" data-anchor-id="모형의-비교"><span class="header-section-number">7.5.7</span> 모형의 비교</h3>
<p>위에서 고려한 임의계수모형 <a href="#eq-repeat" class="quarto-xref">식&nbsp;<span>7.12</span></a> 에서는 절편과 기울기에 대한 2개의 임의효과 <span class="math inline">\(b_{0i}\)</span> 와 <span class="math inline">\(b_{1i}\)</span> 를 고려하고 더 나아가 두 개의 임의효과가 독립이 아니며 상관계수가 <span class="math inline">\(\rho\)</span>라고 가정하였다.</p>
<p>앞에서 추정결과에 의하면 두 개의 임의효과의 상관계수의 추정값은 <span class="math inline">\(\hat \rho = 0.066\)</span> 으로 거의 0에 가깝다. 이러한 결과에 근거하여 두 임의효과가 독립인 축소모형을 고려해 보자. 즉 임의계수모형 <a href="#eq-repeat" class="quarto-xref">식&nbsp;<span>7.12</span></a> 에서 임의효과의 상관계수가 <span class="math inline">\(\rho=0\)</span>인 임의효과의 분포를 다음과 같이 가정한다.</p>
<p><span class="math display">\[
\begin{bmatrix}
b_{0i} \\
b_{1i} \\
\end{bmatrix} \sim
N \left (
\begin{bmatrix}
0 \\
0 \\
\end{bmatrix}
,
\begin{bmatrix}
\sigma^2_{b1} &amp; 0\\
0 &amp; \sigma^2_{b2} \\
\end{bmatrix}
\right )
\]</span></p>
<p>이러한 모형을 아래와 같이 적합시키면 추정결과는 다음과 같다. 아래 모형식에서 <code>(1 + Days||Subject)</code> 는 각 개체 <code>Subject</code> 에 대하여 절편 <code>1</code> 과 기울기 <code>Days</code>에 임의효과를 포함한다고 지정하며 한개의 바 <code>|</code> 대신 두 개의 바 <code>||</code> 를 사용하면 임의효과가 독립이라는 것을 지정한다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>fm2 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(Reaction <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> Days <span class="sc">+</span> (<span class="dv">1</span><span class="sc">+</span>Days <span class="sc">||</span> Subject) , sleepstudy)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fm2)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: Reaction ~ 1 + Days + (1 + Days || Subject)
   Data: sleepstudy

REML criterion at convergence: 1743.7

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.9626 -0.4625  0.0204  0.4653  5.1860 

Random effects:
 Groups    Name        Variance Std.Dev.
 Subject   (Intercept) 627.57   25.051  
 Subject.1 Days         35.86    5.988  
 Residual              653.58   25.565  
Number of obs: 180, groups:  Subject, 18

Fixed effects:
            Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)  251.405      6.885  18.156  36.513  &lt; 2e-16 ***
Days          10.467      1.560  18.156   6.712 2.59e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
     (Intr)
Days -0.184</code></pre>
</div>
</div>
<p>상관계수가 0인 모형에 대한 추정 결과는 상관계수가 있는 모형과 크게 다르지 않다.</p>
<p>두 모형, 즉 절편과 기울기에 대한 두 임의효과가 종속인지 또는 독립인지에 대한 두 모형을 AIC(Akaike Information Criteris)와 BIC(Bayesian Information Criteria)로 비교한 결과이다. 두 모형 간의 차이는 거의 없는 것으로 판단된다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">AIC</span>(fm1) , <span class="fu">BIC</span>(fm1))</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1755.628 1774.786</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="fu">AIC</span>(fm2), <span class="fu">BIC</span>(fm2))</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1753.669 1769.634</code></pre>
</div>
</div>
<p>더나아가 <code>anova</code> 함수를 이용하여 두 모형의 차이를 검정한 결과는 두 모형 간의 차이가 없다는 것이다. 참고할 점은 혼합모형에서의 모형을 비교하는 분산분석에 의한 검정은 효율이 떨어질 수 있기 때문에 주의해야 한다.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fm1,fm2)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>refitting model(s) with ML (instead of REML)</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Data: sleepstudy
Models:
fm2: Reaction ~ 1 + Days + (1 + Days || Subject)
fm1: Reaction ~ 1 + Days + (1 + Days | Subject)
    npar    AIC    BIC  logLik deviance  Chisq Df Pr(&gt;Chisq)
fm2    5 1762.0 1778.0 -876.00   1752.0                     
fm1    6 1763.9 1783.1 -875.97   1751.9 0.0639  1     0.8004</code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "복사완료!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "복사완료!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    const typesetMath = (el) => {
      if (window.MathJax) {
        // MathJax Typeset
        window.MathJax.typeset([el]);
      } else if (window.katex) {
        // KaTeX Render
        var mathElements = el.getElementsByClassName("math");
        var macros = [];
        for (var i = 0; i < mathElements.length; i++) {
          var texText = mathElements[i].firstChild;
          if (mathElements[i].tagName == "SPAN") {
            window.katex.render(texText.data, mathElements[i], {
              displayMode: mathElements[i].classList.contains('display'),
              throwOnError: false,
              macros: macros,
              fleqn: false
            });
          }
        }
      }
    }
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        typesetMath(container);
        return container.innerHTML
      } else {
        typesetMath(note);
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      typesetMath(note);
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../notes/poisson.html" class="pagination-link  aria-label=" &lt;span="" 회귀모형&lt;="" span&gt;"="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">포아송 회귀모형</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../notes/spline-01.html" class="pagination-link" aria-label="<span class='chapter-number'>8</span>&nbsp; <span class='chapter-title'>국소 회귀모형</span>">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">국소 회귀모형</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>